### ISSUE TITLE
[BUG] Override_state doesn't work for home. 

### ISSUE THREAD

**Issue by stroodle96** [flixlix/power-flow-card-plus#108]
**Describe the bug**
I set override_state: true for home config.  It still shows the grid consumption total and not the value of the entity I set. 

**To Reproduce**
I will just paste my yaml below:

```yaml
title: Power Flow Card
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.victron_shore_power_input
    display_state: one_way
    color_circle: true
    icon: mdi:power-plug
    name: Shore Power
  battery:
    entity: sensor.eg4_ll_battery_load_watts
    state_of_charge: sensor.eg4_ll_battery_percent
    display_state: one_way
    color_circle: true
  home:
    color_icon: true
    name: Camper
    icon: mdi:rv-truck
    override_state: true
    entity: sensor.victron_ac_loads
    secondary_info:
      entity: sensor.victron_ac_loads
  individual1:
    entity: sensor.fridge_plug_instantaneous_demand
    icon: mdi:fridge
    color: '#80b8ff'
    name: Fridge AC
    color_icon: false
    display_zero: true
  individual2:
    entity: sensor.starlink_power_plug_instantaneous_demand
    icon: mdi:satellite-uplink
    color: '#80b8ff'
    name: Starlink
    color_icon: false
    display_zero: true
watt_threshold: 10000
clickable_entities: true
use_new_flow_rate_model: true
```

**Expected behavior**
I expected the home to display the value of the sensor.victron_ac_loads sensor. You can see in the screenshot below it correctly displays it for secondary info, but not the main entity. 

**Screenshots**
![Screenshot_20230419_150751_Home Assistant](https://user-images.githubusercontent.com/43659890/233175795-0e477b42-eca3-409e-a053-eaf6f7c150c4.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 Ultra
 - OS: Android
 - Browser companion app
 
**Additional context**
Also looked in a new browser session and issue persists. 

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [ x] I have the latest version of the card installed.

- [ x] I have cleared my browser cache **after** installing, updating and configuring the card.
