### ISSUE TITLE
Add option for "Gas" (or already possible?)

### ISSUE THREAD

**Issue by Vinisz** [flixlix/power-flow-card-plus#113]
Hi,

Thanks for this card, very nice....
Can you add the option to add "gas" consumption ? (or if already possible can you tell me how)
Should look the same as with the normal energy card

**Comment by flixlix** [comment]
Do you mean this?

<img width="500" alt="Bildschirmfoto 2023-04-20 um 21 54 55" src="https://user-images.githubusercontent.com/61006057/233473888-e0ccc15f-ac7d-4469-8b00-330e19ba1aae.png">

```yaml
  individual1:
    color_icon: true
    color_value: 'true'
    inverted_animation: true
    display_zero: true
    display_zero_state: false
    entity: sensor.gas_usage
    icon: mdi:fire
    color: "#FF3D12"
    name: Gas
```
