### ISSUE TITLE
[OTHER] How will be the "CO2 Signal" Sensor be calculated (percentage) ?

### ISSUE THREAD

**Issue by ChristophCaina** [flixlix/power-flow-card-plus#114]
Hi,
I am currently playing arround with some of the options of the power-flow-card plus... and testing the CO2 signal information...

```
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:leaf
    color_icon: true
    display_zero: true
    name: Non Fossil
    state_type: percentage
```
In this case, I've set the state_type to percentage... which gives me a value of 62%
![image](https://user-images.githubusercontent.com/26391061/233551734-31591f26-baf5-4333-8792-21f49cc1ada2.png)

How does the calculation work?
CO2 signal provides 38% "total" ...
and if I switch to state_type: power, the card is showing 0W - since I do have solar export...

![image](https://user-images.githubusercontent.com/26391061/233551908-1cf0309e-1fe6-4881-a749-c67438cb9296.png)
