### ISSUE TITLE
[FEATURE REQUEST] - Show Secondary Information for fossil fuel

### ISSUE THREAD

**Issue by ChristophCaina** [flixlix/power-flow-card-plus#115]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to add a secondary information to the "CO2 Sensor"
The secondary info should be (in this case) the co2-sensor percentage value, like it can be done for the electric vehicle or battery (State of Charge)
![image](https://user-images.githubusercontent.com/26391061/233605474-0a9c426f-1c20-4af9-9234-7a635d1004e1.png)

**Describe the solution you'd like**
yaml code could look like this one:

```
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:leaf
    color_icon: true
    display_zero: true
    name: Non Fossil
    state_type: power
    secondary_info:
      entity: sensor.co2_signal_grid_fossil_fuel_percentage
      unit_of_measurement: '%'
      state_type: percentage
``` 

**Describe alternatives you've considered**

**Additional context**

**Comment by flixlix** [comment]
This is already possible in the v0.1beta using templates:

```yaml
  fossil_fuel_percentage:
    entity: sensor.grid_fossil_fuel_percentage
    display_zero: true
    secondary_info:
      color_value: true
      unit_of_measurement: '%'
      template: >-
        {{100 - (states("sensor.grid_fossil_fuel_percentage")|float) |
        round(0)}} %
    state_type: power
    color_icon: true
    color_value: true
    unit_white_space: true
    display_zero_state: true
    display_zero_tolerance: 10
```

**Comment by ChristophCaina** [comment]
thanks :)
One short thing since I don't know if this is related to the Beta - and already known:

It seems that - when secondary information is enabled, the power value will not be shown.
```
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    display_zero: true
    secondary_info:
      color_value: true
      unit_of_measurement: '%'
      template: >-
        {{100 - (states("sensor.co2_signal_grid_fossil_fuel_percentage")|float) |
        round(0)}} %
    state_type: power
    color_icon: true
    color_value: true
    unit_white_space: true
    display_zero_state: true
    display_zero_tolerance: 10
```
![image](https://user-images.githubusercontent.com/26391061/233610122-14520fdd-5666-42f2-af70-89698b836c2c.png)

Or might this be an issue with my cache?

**Comment by flixlix** [comment]
<img width="96" alt="Bildschirmfoto 2023-04-21 um 12 24 29" src="https://user-images.githubusercontent.com/61006057/233613186-76e4910c-d03f-4ac9-b951-e40ef709e6ba.png">
hmm, I'm not experiencing this issue, so maybe it can be fixed by clearing your cache.
Judging by your configuration, everything looks fine and should work alright...
Can you try reinstalling the beta version and clearing your cache?

**Comment by ChristophCaina** [comment]
I already did it - but I will give it another try and Report BackGesendet von Outlook für Android

**Comment by ChristophCaina** [comment]
hm... seems to be something with my system... ?!

removed the card - cleared the cache and reinstalled the beta again.
On Chrome, still the same.
On Chrome for Android, the same.
On Edge (Chrome engine) it appears to be the same (not used before this test, so nothing should have been cached in the browser itself)

In general, it seems to be working... I've tried to set a secondary info for the house consumption (based on solar production) - which is at least showing the template, because I think the secondary info hasn't been implemented for this.
![image](https://user-images.githubusercontent.com/26391061/233618408-28fe2ad6-e8e4-453d-9183-6cb17eb4650f.png)

Another - maybe interesting thing seems to be:
I've downloaded v0.9.6 again - but kept the config the same.
Then - after deleting cache / reloading - it did show the W output.
I've installed 0.1 beta again, did another reload - and now I have again only the percentage...

**Comment by flixlix** [comment]
If your configuration still looks like this, then the is the reason it's not showing is that you are exporting to the grid:

```yaml
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:leaf
    color_icon: true
    display_zero: true
    name: Non Fossil
    state_type: power
    secondary_info:
      entity: sensor.co2_signal_grid_fossil_fuel_percentage
      unit_of_measurement: '%'
      state_type: percentage
```

Try using this configuration (adds `display_zero_state`):

```yaml
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:leaf
    color_icon: true
    display_zero: true
    display_zero_state: true
    name: Non Fossil
    state_type: power
    secondary_info:
      entity: sensor.co2_signal_grid_fossil_fuel_percentage
      unit_of_measurement: '%'
      state_type: percentage
```

If it already looks like this, we might look into that further, because I revisited the conditions for the state of the `fossil_fuel_percentage` state and nothing on there seems to be conflicting with the `secondary_info`.

**Comment by ChristophCaina** [comment]
hm... indeed... it seems to be related to the Import / export:

while importing energy:
![grafik](https://user-images.githubusercontent.com/26391061/233668665-8b51b5ee-e1cf-4ef9-966f-96194b80b9fa.png)

and here without import:
![grafik](https://user-images.githubusercontent.com/26391061/233668719-2ae57610-7156-4674-a956-0b3910a93317.png)

but it seems to ignore the parameter "display_zero_state: true"
```
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:leaf
    color_icon: true
    display_zero: true
    display_zero_state: true
    name: Non Fossil
    state_type: power
    secondary_info:
      unit_of_measurement: '%'
      template: >-
        {{100 - (states("sensor.co2_signal_grid_fossil_fuel_percentage")|float)
        | round(0)}} %
```
