### ISSUE TITLE
Allow 2x 'Grid' inputs for Electric and Gas (UK)

### ISSUE THREAD

**Issue by lucky81** [flixlix/power-flow-card-plus#124]
The following config would be ideal for the UK where house typical have both gas and electric supply, but 2x 'grid' is not allowed. Please update to allow for 2x 'grid'.

```yaml
type: custom:power-flow-card-plus
title: Energy Usage
entities:
  grid:
    name: Electric
    icon: mdi:transmission-tower
    entity: >-
      sensor.electricity_z18n085000_2000013563684_previous_accumulative_consumption
    display_state: one_way
    color_circle: true
    color:
      consumption: '#7DF9FF'
  grid:
    name: Gas
    icon: mdi:fire
    entity: >-
      sensor.gas_e6s11459991860_5072960800_previous_accumulative_consumption
    display_state: one_way
    color_circle: true
    color:
      consumption: '#FC8A17'
```
