### ISSUE TITLE
[OTHER] Might be missing something but fossil card not showing

### ISSUE THREAD

**Issue by JRascagneres** [flixlix/power-flow-card-plus#127]
I have added the fossil percentage and I can see the home circle is colored with a certain percentage:
![image](https://user-images.githubusercontent.com/3264971/234698031-174cd587-9180-4031-9665-bf48bf8c7b03.png)

However it doesn't seem to show the fossil line separately like in the examples. Am I missing something?

```
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.smart_meter_electricity_current
    display_state: one_way
    color_circle: true
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Non Fossil
    state_type: percentage
    display_zero_state: true
    color_value: false
  home: {}

```
