### ISSUE TITLE
[BUG] kWh unit not shown in energy entities

### ISSUE THREAD

**Issue by heinemannj** [flixlix/power-flow-card-plus#159]
**Describe the bug**
Update to the latest card version this morning: `0.1.1`
I'm expecting that after your last fixes Energy Entities are displayed in kWh as defined by the HA sensors.

In addition the low carbon bullet are displayed in W and not in kW.

**To Reproduce**
```
    type: custom:power-flow-card-plus
    title: Energy Flows (Today) - power-flow-card-plus
    min_flow_rate: 3
    max_flow_rate: 10
    watt_threshold: 0
    kw_decimals: 3
    w_decimals: 0
    clickable_entities: true
    entities:
      home: null
      solar:
        entity: sensor.solar_yield_daily
      battery:
        entity:
          consumption: sensor.battery_day_discharge_with_loss
          production: sensor.battery_day_charge_with_loss
        state_of_charge: sensor.battery_state_of_capacity
        color_circle: true
      grid:
        entity:
          consumption: sensor.power_meter_consumption_energy_daily
          production: sensor.power_meter_exported_energy_daily
      fossil_fuel_percentage:
        entity: sensor.co2_signal_grid_fossil_fuel_percentage
        icon: mdi:pine-tree
        color_icon: true
        display_zero: true
        name: Low-carbon
        state_type: power
```

**Expected behavior**
Entity units should be displayed as defined by the HA sensors.

**Screenshots**

![image](https://user-images.githubusercontent.com/3251642/236748327-4a4cef0d-a44c-4e7c-bcb2-1c5c58d86b7e.png)

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: Chrome

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.
