### ISSUE TITLE
[FEATURE REQUEST] Generator Input

### ISSUE THREAD

**Issue by legomind** [flixlix/power-flow-card-plus#161]
I know this has been asked before, but I wanted to weigh in because I have a slightly different use case.
I have a solar system with a battery bank as well as a portable generator operating as a standby generator.
Since the generator is not large enough to run my house without load-shedding, I have it connected to an eg4 100amp battery charger.

In the event the grid goes down and my solar production is not enough to keep the battery charged over 30%, the generator is started and begins to charge the battery using the eg4 chargeverter. I have integrated the battery charger into home assistant using modbus, so I can track how much energy is put into the battery from the generator.

Ideally, this card would allow me to show the generator outputting power into the battery.

Maybe something like this:

```yaml
type: custom:power-flow-card-plus
dashboard_link: /energy
use_new_flow_rate_model: true
watt_threshold: 101
entities:
  home:
    entity: sensor.solark_load_power
  grid:
    entity: sensor.solark_grid_external_total_power
  solar:
    entity: sensor.solark_pv_input_power
  battery:
    entity: sensor.solark_battery_power
    state_of_charge: sensor.solark_battery_state_of_charge
  generator:
    entity: sensor.generator_dc_output_power
    connected_to: battery # or home, for those with generators directly connected to loads

```
I am terrible with gimp, but here is a mockup...
![generator_mockup](https://user-images.githubusercontent.com/3710857/236823224-1f5cad21-e6d4-47b5-878d-95a222ff73df.png)
