### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Indianagrenoble** [flixlix/power-flow-card-plus#162]
Amazing job ! Many thanks !!!

So I try everything many times and I have the same direction  issue with my Battery ... 

When it's charging (battery comsumption also it should be inverted like this) :  Direction should be from grid or solar to the Battery
When it's decharging : Direction comes from battery to Grid or to Home...

I think so, if possible to have an "inversion" of Bettery direction ?!

**Comment by flixlix** [comment]
use `inverted_entities: battery` for your main configuration. Does this solve your issue

**Comment by Indianagrenoble** [comment]
I'm a beginner and I don' know where to put this "inverted_entities: battery"

my YAML : 
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.victron_ac_l1
    color_icon: true
    color_value: true
    subtract_individual: false
    override_state: false
    secondary_info:
      color_value: true
      icon: mdi:water-boiler
  fossil_fuel_percentage:
    entity: sensor.co2_signal_co2_intensity
    icon: mdi:leaf
    color_icon: true
    display_zero: false
    name: Non Fossil
    state_type: power
    color_value: true
    display_zero_state: false
  grid:
    icon: mdi:transmission-tower-import
    name: Provider
    entity: sensor.victron_grid_load
    color_icon: true
    color_circle: true
    color:
      consumption:
        - 231
        - 13
        - 13
      production:
        - 30
        - 16
        - 218
  solar:
    icon: mdi:solar-panel-large
    entity: sensor.solarnet_power_photovoltaics
    secondary_info:
      entity: sensor.pv_cave_power
      color_value: true
      unit_white_space: true
    color_value: true
    color_icon: true
  battery:
    name: Batterie
    icon: mdi:battery-charging-100
    entity: sensor.victron_battery_power_system
    state_of_charge: sensor.victron_battery_state_of_charge_system
    color_icon: true
    color_circle: true
    display_state: one_way_no_zero
    color_state_of_charge_value: true
    color:
      consumption:
        - 0
        - 230
        - 15
      production:
        - 242
        - 2
        - 2
  individual1:
    entity: sensor.ballon_ec_power
    icon: mdi:water-boiler
    color: '#80b8ff'
    color_icon: true
    color_value: true
  individual2:
    entity: sensor.motorbike_power
    name: Qivi
    color_icon: true
    display_zero: true
    color: '#ff8080'
    icon: mdi:motorbike-electric
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 10000
clickable_entities: true
title: Flux énergétiques Le Bruyant
display_zero_lines: true
use_new_flow_rate_model: true

**Comment by flixlix** [comment]
No problem, try using this configuration 🙂:

```yaml
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.victron_ac_l1
    color_icon: true
    color_value: true
    subtract_individual: false
    override_state: false
    secondary_info:
      color_value: true
      icon: mdi:water-boiler
  fossil_fuel_percentage:
    entity: sensor.co2_signal_co2_intensity
    icon: mdi:leaf
    color_icon: true
    display_zero: false
    name: Non Fossil
    state_type: power
    color_value: true
    display_zero_state: false
  grid:
    icon: mdi:transmission-tower-import
    name: Provider
    entity: sensor.victron_grid_load
    color_icon: true
    color_circle: true
    color:
      consumption:
        - 231
        - 13
        - 13
      production:
        - 30
        - 16
        - 218
  solar:
    icon: mdi:solar-panel-large
    entity: sensor.solarnet_power_photovoltaics
    secondary_info:
      entity: sensor.pv_cave_power
      color_value: true
      unit_white_space: true
    color_value: true
    color_icon: true
  battery:
    name: Batterie
    icon: mdi:battery-charging-100
    entity: sensor.victron_battery_power_system
    state_of_charge: sensor.victron_battery_state_of_charge_system
    color_icon: true
    color_circle: true
    display_state: one_way_no_zero
    color_state_of_charge_value: true
    color:
      consumption:
        - 0
        - 230
        - 15
      production:
        - 242
        - 2
        - 2
  individual1:
    entity: sensor.ballon_ec_power
    icon: mdi:water-boiler
    color: '#80b8ff'
    color_icon: true
    color_value: true
  individual2:
    entity: sensor.motorbike_power
    name: Qivi
    color_icon: true
    display_zero: true
    color: '#ff8080'
    icon: mdi:motorbike-electric
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 10000
clickable_entities: true
title: Flux énergétiques Le Bruyant
display_zero_lines: true
use_new_flow_rate_model: true
inverted_entities: battery
```

The only change I made was the last line
