### ISSUE TITLE
[BUG] Since update to 0.1.1 flow dots no longer displaying

### ISSUE THREAD

**Issue by e10kstarfire** [flixlix/power-flow-card-plus#165]
**Describe the bug**
I only see the flow dots moving between low carbon and grid, all other moving dost have stopped

**To Reproduce**
Updated from 0.1 to 0.1.1, no other changes. Was working fine prior to update.

**Expected behavior**
Dots moving from battery, grid, solar etc

**Screenshots**
n/a

**Desktop (please complete the following information):**
Firefox browser on Linux

**Additional context**
This is my config:
```
type: custom:power-flow-card-plus
watt_threshold: 999
clickable_entities: true
entities:
  fossil_fuel_percentage:
    display_zero: true
    state_type: percentage
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
  home:
    entity: sensor.givtcp_ed225XXXXX_load_power
    override_state: true
  grid:
    display_state: one_way
    entity:
      consumption: sensor.givtcp_ed225XXXXX_import_power
      production: sensor.givtcp_ed225XXXXX_export_power
  solar:
    entity: sensor.givtcp_ed225XXXXX_pv_power
  battery:
    display_state: one_way
    entity:
      consumption: sensor.givtcp_ed225XXXXX_discharge_power
      production: sensor.givtcp_ed225XXXXX_charge_power
    state_of_charge: sensor.givtcp_ed225XXXXX_soc
  individual1:
    entity: sensor.myenergi_eddi_power_charging
    icon: mdi:shower
    name: Hot Water
    display_zero: true
    secondary_info:
      entity: sensor.myenergi_eddi_status
```

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X ] I have the latest version of the card installed.

- [X ] I have cleared my browser cache **after** installing, updating and configuring the card.
