### ISSUE TITLE
Incorrect consumption shown

### ISSUE THREAD

**Issue by SheriffOfNotts** [flixlix/power-flow-card-plus#181]
I've configured the card (which is excellent btw), but one of the entities isn't showing the correct kWh?

The card config is as below and I've included images of the sensor and the [output..

```yaml
type: custom:power-flow-card-plus
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 0
clickable entities: true
entities:
  home:
    entity: sensor.smart_meter_electricity_power
    color_icon: true
  grid:
    name: Grid
    entity:
      consumption: sensor.smart_meter_electricity_power
      display_state: one_way
      color_icon: null
  individual1:
    entity: sensor.id_3_charge_power
    name: ID.3
    icon: mdi:car-electric
    display_zero: true
  individual2:
    entity: sensor.it_kit_current_power
    name: IT Kit
    icon: mdi:router-network
    display_zero: true
```

<img width="645" alt="Screenshot 2023-05-19 at 08 20 30" src="https://github.com/flixlix/power-flow-card-plus/assets/16319499/d7cd23f6-7f45-4bc9-9729-fa4e4338e268">
<img width="560" alt="Screenshot 2023-05-19 at 08 19 59" src="https://github.com/flixlix/power-flow-card-plus/assets/16319499/ec9fc53a-434a-4cb0-9182-4449a62e8351">
