### ISSUE TITLE
Inverted_state not working

### ISSUE THREAD

**Issue by finalbillybong** [flixlix/power-flow-card-plus#196]
Perhaps I have not got my config correct but the new interted_state is not working correctly for me.

Old yaml that worked:
```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_usage_template
    state_of_charge: sensor.solis_battery_soc
  grid:
    entity: sensor.solis_grid_active_power
  solar:
    entity: sensor.solis_inverter_dc_power
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
  individual1:
    entity: sensor.utility_usage_template
    icon: mdi:washing-machine
    name: Utilities
    color: '#FF3333'
    color_icon: false
    display_zero: true
  individual2:
    entity: sensor.myenergi_zappi_21782493_internal_load_ct1
    icon: mdi:car-electric
    name: Car
    color: '#33FF58'
    color_icon: false
    display_zero: true
dashboard_link: /energy
watt_threshold: 999
title: Real Time Power Usage
inverted_entities: battery, grid, fossil_fuel_percentage
````

New yaml that does not work:

```
type: custom:power-flow-card-plus
entities:
  battery:
    inverted_state: true
    entity: sensor.battery_usage_template
    state_of_charge: sensor.solis_battery_soc
  grid:
    inverted_state: true  
    entity: sensor.solis_grid_active_power
  solar:
    entity: sensor.solis_inverter_dc_power
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
  individual1:
    entity: sensor.utility_usage_template
    icon: mdi:washing-machine
    name: Utilities
    color: '#FF3333'
    color_icon: false
    display_zero: true
  individual2:
    entity: sensor.myenergi_zappi_21782493_internal_load_ct1
    icon: mdi:car-electric
    name: Car
    color: '#33FF58'
    color_icon: false
    display_zero: true
dashboard_link: /energy
watt_threshold: 999
title: Real Time Power Usage
```
