### ISSUE TITLE
[OTHER] Question regarding battery and other things

### ISSUE THREAD

**Issue by tretabyte** [flixlix/power-flow-card-plus#203]
Hi,
have a couple of questions that I can't get enough information from the readme + wiki (sorry if they were already asked but I also checked every case open and couldn't find anything explicit for this), so this is regarding the battery usage In/Out, are we supposed to have an additional sensor that will automatically show is the battery is pulling power or sending power?
these are the sensors I can pull from my inverter (there's more but nothing related to battery or power usage):
![image](https://github.com/flixlix/power-flow-card-plus/assets/60727013/f86d56bd-aed1-40b6-bb60-b5cac843a221)
from the list I see I have Battery Input energy today and Output energy today but I don't really think these should be the ones to be used for productions/consumption or should them? (because the values are a bit weird like within the card)

Another question is related to Home, I should use the home labled 'house load' which shows some instant value in W, when I look at the card it shows something totally different, is Home a sum of different factors?
At the time of the screenshot you can see 2 different values, one from the sensor itself and the other showing in the card
![image](https://github.com/flixlix/power-flow-card-plus/assets/60727013/fe90f88f-fed7-40a9-b82e-79bb276e5ffd)

last question (for now at least sorry :\), related to fossil_fuel_percentage, there's a screenshot that shows in the same circule, state power and percentage, how can I do that?

ps: the card now supposely supports UI configuration but I can only access yaml, dunno why (I'm using the latest stable version)
when I create a new blank card I automatically get this:
![image](https://github.com/flixlix/power-flow-card-plus/assets/60727013/d173ba15-96c1-4c07-b707-9b79cc8d6f77)

This is the code for the card I'm building atm:
```
type: custom:power-flow-card-plus
entities:
  fossil_fuel_percentage:
    entity: sensor.grid_fossil_fuel_percentage
    color_icon: true
    display_zero: true
    state_type: power
  grid:
    entity:
      consumption: sensor.solax_x1_hybrid_g3_grid_import
      production: sensor.solax_x1_hybrid_g3_grid_export
      display_state: one_way
      color_circle: true
  solar:
    entity: sensor.solax_x1_hybrid_g3_pv_power_total
  battery:
    entity:
      consumption: sensor.solax_x1_hybrid_g3_battery_output_energy_today
      production: sensor.solax_x1_hybrid_g3_battery_input_energy_today
    state_of_charge: sensor.solax_x1_hybrid_g3_battery_capacity
    display_state: one_way
    color_circle: true
  home:
    entity: sensor.solax_x1_hybrid_g3_house_load
    color_icon: true
w_decimals: 0
kw_decimals: 2
watt_threshold: 10000
clickable_entities: true
use_new_flow_rate_model: true
```

**Comment by flixlix** [comment]
## Which Entities to use?

It would be easier for me if you opened one issue for each question, but I'll try my best to respond to every question.

Depending on what you want to achieve, you should choose one of these cards:

1. You want to display instantaneous power (eg: "What are my solar panels producing right now?").
    - In this case this card is the right use case.
    - Your sensors should have the unit of `W` or `kW` **(not `Wh` or `kWh`)**
2. You want to display accumulated energy over a certain period of time (eg: "How much did my sola panels produce this week?")
    - In this case you should use my [Energy Flow Card Plus](https://github.com/flixlix/energy-flow-card-plus)
    - There, your sensors should have the unit of `Wh` or `kWh`

For this card I assume the correct entity from your integration would be the "Battery Power Charge", assuming it has positive values for one direction and negative values for the other direction.

## Why is the state of Home completely off?

By default the Card calculates the home power based on the different energy sources you have defined, so if only one source is wrongly configured, the calculation will result in something unexpected.

In this case it is probably because you are not using the correct entities for your home battery, try using the "Battery Power Charge" entity like I mentioned above.

If, for some reason, you really want to use the state from that sensor to be displayed, you can use this (I recommend configuring all Sources correctly first):

```yaml
home: 
  entity: sensor.YOUR_HOME_POWER
  override_state: true
```

## How can I display Non-Fossil Percentage and Power at the same time?

This is relatively simple:

```yaml
fossil_fuel_percentage:
  entity: sensor.YOUR_CO2_SIGNAL_SENSOR
  state_type: power
  secondary_info:
    entity: sensor.YOUR_CO2_SIGNAL_SENSOR
```

In the main state the percentage is multiplied with the grid consumption. In the secondary info, the state of your sensor is being taken directly. If I recall correctly, I used a template for the secondary_info field, because the sensor shows how much **is** high-fossil, so you would have to invert that with a template.

## Why is my UI-Editor not working?

This issue has been opened about 10 times before 😅
It's a known issue caused by card-mod, here is the fix taken from the readme:

> ⚠️ Version 0.1 introduced the UI Editor. This Editor is currently incompatible with Card Mod. I created a PR to fix this issue, but it hasn't been merged yet. Here is the [PR #277](https://github.com/thomasloven/lovelace-card-mod/pull/277). Since it hasn't been merged yet, I also released a fork with the changes from the PR. Installing this Version of Card Mod you can use this card in conjunction with Card Mod. [Here is my fork](https://github.com/flixlix/lovelace-card-mod)

<hr/>

<b>Does this fix your issues?</b>

**Comment by tretabyte** [comment]
Hi,

thank you very much for the long explanation and sorry for not opening several tickets, will do next time (hope not!).
regarding the battery, this is what I have:
```
  battery:
    entity:
      consumption: sensor.solax_x1_hybrid_g3_battery_output_energy_today
      production: sensor.solax_x1_hybrid_g3_battery_input_energy_today
    state_of_charge: sensor.solax_x1_hybrid_g3_battery_capacity
    display_state: one_way
    color_circle: true
```
you suggested sensor.solax_x1_hybrid_g3_battery_power_charge which does give me positive and negative values but the card asks for 2, should I repeat it twice?
![image](https://github.com/flixlix/power-flow-card-plus/assets/60727013/32286413-4862-4820-a542-704a169ce92b)
