### ISSUE TITLE
[BUG] Power incorrectly flows from solar to battery when there is no surplus solar

### ISSUE THREAD

**Issue by TheodorKleynhans** [flixlix/power-flow-card-plus#227]
**Describe the bug**
Power incorrectly flows from solar to battery when there is no surplus solar.

**To Reproduce**
1. Configure the cards as in the screenshot below (fairly close to default).
2. Wait for the home to consume more power than is being exported from solar (e.g. at night or cloudy day).
3. Configure the inverter to increase the battery state of charge.

**Expected behavior**
If the load (home) consumes all of the solar export, nothing should flow from solar to battery. If the battery is still receiving power, it must be coming from the grid.
In the screenshot below, I would expect the following power flows:
 - Solar to Home
 - Eskom (grid) to Home
 - Eskom (grid) to Battery

**Screenshots**
![IncorrectFlowFromSolarToBattery](https://github.com/flixlix/power-flow-card-plus/assets/20594743/9820cff8-8ecb-4b78-abd3-625cfd778026)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 113.0.5672.127

**Additional context**
Seems to be broken from v1.4.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by BVGorp** [comment]
![2023-05-30_11-32-51 (1)](https://github.com/flixlix/power-flow-card-plus/assets/31847345/86d11b4e-1f42-4ecd-96b3-55246cac77a5)

Also an issue without battery

**Comment by BVGorp** [comment]
ok re-downloading v0.1.4.1 fixed it for me

**Comment by TheodorKleynhans** [comment]
Unfortunately, it is definitely broken for me in v0.1.4.1.
I downloaded and installed all the following versions:
- v0,1.4.1
- v0.1,4
- v0.1.4b
- v0.1.3

Only the last (v0.1.3) fixed it. Also, I just noticed that all versions later than v0.1.3 do not display the `Low-carbon` circle, even though the corresponding % is shaded green in the `home` circle (also visible in my screenshot in the OP).

**Comment by flixlix** [comment]
Can you share your code and the state of each entity, so that I can debug this issue further?

**Comment by TheodorKleynhans** [comment]
Sure, whatever I can do to help.

Here is the YAML:

``` yaml
type: custom:power-flow-card-plus
entities:
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    color_icon: true
    display_zero: false
    state_type: power
    display_zero_tolerance: 1
  grid:
    name: Eskom
    entity: sensor.grid_power
    color_icon: true
    color_circle: true
    power_outage:
      entity: binary_sensor.load_shedding
      label_alert: Load Shedding
    display_state: one_way
  home:
    color_icon: true
    subtract_individual: false
    entity: sensor.load_power
    override_state: true
  solar:
    entity: sensor.pv_power
    color_icon: true
  battery:
    entity: sensor.battery_power
    state_of_charge: sensor.battery_state_of_charge
    color_icon: true
    color_circle: true
    display_state: one_way
    invert_state: true
  individual1:
    entity: sensor.geyser_power
    name: Geyser
    icon: mdi:heating-coil
    display_zero: false
    color_value: true
    color_icon: true
    display_zero_state: false
  individual2:
    entity: sensor.pool_pump_power
    display_zero_tolerance: 50
    display_zero: false
    color_icon: true
    color_value: true
    name: Pool Pump
    icon: ''
    inverted_animation: false
w_decimals: 0
kw_decimals: 2
use_new_flow_rate_model: true
watt_threshold: 1000
clickable_entities: true
```

Sensors:

- `sensor.co2_signal_grid_fossil_fuel_percentage` = 82.05
- `sensor.grid_power` = 10176
- `sensor.load_power` = 3361
- `sensor.pv_power` = 4 (the sun is not currently shining)
- `sensor.battery_power` = 6205 (charging)
- `sensor.battery_state_of_charge` = 40
