### ISSUE TITLE
Shows an empty card

### ISSUE THREAD

**Issue by ssorgatem** [flixlix/power-flow-card-plus#24]
No matter what I put in the config, all it shows is... nothing. An invisible card, just an empty card, even when using the same confg that worked for power-glow-card and for this fork before the name change.

**Comment by flixlix** [comment]
Can you try this from the minimal configuration from the README?
```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.grid_consumption
      production: sensor.grid_production
  solar:
    entity: sensor.solar_production
```

> Please replace the entity ids with known working ones in your setup

**Comment by ssorgatem** [comment]
But I have a different problem now: I have a single entity that measures grid consumption (in negative) and export (in positive). It worked well with "inverted_entities: grid" but now it doesn't and shows production as consumption.

**Comment by flixlix** [comment]
Can you please share your code?

**Comment by ssorgatem** [comment]
I think I got it working, without inverted_entities thpugh, only using "production"... but I'm not sure it will work when I start importing from the grid:

```
title: Energia a temps real
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      production: sensor.power_meter_active_power
  solar:
    entity: sensor.inverter_active_power
  individual1:
    entity: sensor.regleta_tl_power
    name: Ordinador
    icon: mdi:monitor
    color: '#ff0000'
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    color_icon: true
    display_zero: true
    state_type: power
w_decimals: 0
kw_decimals: 2
```

![image](https://user-images.githubusercontent.com/108138/227995928-a50f4e84-a786-49d8-9d9c-d9459f8c33d3.png)

**Comment by ssorgatem** [comment]
Before (power-flow-card)), I had "grid: sensor.power_meter_active_power" and "inverted_entities: grid"

**Comment by flixlix** [comment]
> Before (power-flow-card)), I had "grid: sensor.power_meter_active_power" and "inverted_entities: grid"

This should still work in the current version

**Comment by ssorgatem** [comment]
> > Before (power-flow-card)), I had "grid: sensor.power_meter_active_power" and "inverted_entities: grid"
> 
> This should still work in the current version

It doesn't. The moment I replace the grid section with just "grid: sensor.power_meter_active_power", the card becomes empty or invisible.

**Comment by ssorgatem** [comment]
If I change it to this, it works, though:

```
title: Energia a temps real
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.power_meter_active_power
  solar:
    entity: sensor.inverter_active_power
  individual1:
    entity: sensor.regleta_tl_power
    name: Ordinador
    icon: mdi:monitor
    color: '#ff0000'
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    color_icon: true
    display_zero: true
    state_type: power
inverted_entities: grid
w_decimals: 0
kw_decimals: 2
```

**Comment by ssorgatem** [comment]
Maybe it should raise an error or somethign when using "grid: some_entity" if the "entity:" subsection is now required,rather than silently disappearing

**Comment by flixlix** [comment]
That is weird, I can't replicate this behaviour.
My YAML looks like this:

```yaml
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.home_power
  fossil_fuel_percentage:
    entity: sensor.fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Non Fossil
    state_type: power
  grid:
    display_state: one_way
    entity: sensor.grid_power
  solar:
    icon: mdi:weather-sunny
    entity: sensor.solar_power
  battery:
    display_state: one_way
    state_of_charge: sensor.battery_soc
    entity:
      consumption: sensor.battery_consumption
      production: sensor.battery_production
  individual1:
    entity: sensor.individual1_power
    name: Denim Flash
    icon: mdi:car-electric
    color: '#80b8ff'
    color_icon: false
    secondary_info:
      entity: sensor.individual1_secondary_soc
      unit_of_measurement: '%'
      icon: mdi:battery-charging-medium
  individual2:
    entity: sensor.individual2_power
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 1000000
clickable_entities: true
title: Power Flow Card Plus

```

![image](https://user-images.githubusercontent.com/61006057/228023946-d8f75093-1604-4cc9-a2e8-7c7fed15e288.png)
