### ISSUE TITLE
[BUG] continue circle refresh when enable layout-card 

### ISSUE THREAD

**Issue by andbad** [flixlix/power-flow-card-plus#246]
**Describe the bug**
When I insert the card in a page configured with layout-card (https://github.com/thomasloven/lovelace-layout-card), the card keeps reloading the home circle.

**To Reproduce**
1. Install layout-card mod
2. Create a new view
3. In the view option select "Vertical (layout-card)
4. Insert a new power-flow-card-plus
5. The home circle reload every seconds

**Expected behavior**
The refreash must not reload the circle

**Screenshots**

https://github.com/flixlix/power-flow-card-plus/assets/7837288/82297d5b-bca2-432b-81cd-dd9ebd2e4914

**Desktop (please complete the following information):**
 - OS: ubuntu 
 - Browser: Chrome 
 - Version: 0.1.5

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
I can't see the video you posted, but from the explanation, I followed your steps and wasn't able to replicate the issue.

**Comment by andbad** [comment]
> I can't see the video you posted, but from the explanation, I followed your steps and wasn't able to replicate the issue.

You can see the video here:
https://www.youtube.com/watch?v=dh9Fo0nG6Xg

`By(t)e`

**Comment by heinemannj** [comment]
I have no issues with custom: layout-card and card mod:

https://github.com/heinemannj/home-assistant-config

![image](https://github.com/flixlix/power-flow-card-plus/assets/3251642/3b7b81e6-cf78-4ee1-9d72-2b35598526e5)

```
title: 421-PV
theme: dashboards
path: 421-pv
icon: mdi:solar-power-variant
type: custom:grid-layout
badges: []
cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    cards:
      - !include /config/dashboards/420-pv/cards/420-pv-power-flow-card.yaml
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - !include /config/dashboards/420-pv/cards/420-pv-solar-power-gauge-card.yaml
              - !include /config/dashboards/420-pv/cards/420-pv-battery-capacity-gauge-card.yaml
              - !include /config/dashboards/420-pv/cards/420-pv-battery-status-card.yaml
              - !include /config/dashboards/420-pv/cards/420-pv-self-sufficiency-gauge-card.yaml
              - !include /config/dashboards/420-pv/cards/420-pv-inverter-temp-gauge-card.yaml
              - !include /config/dashboards/420-pv/cards/420-pv-misc-status-card.yaml
            card_mod:
              style: |
                ha-card {
                  width: 915px !important;
                  height: 100px !important;
                  }
          - !include /config/dashboards/420-pv/cards/420-pv-solar-forecast-chart-large-width.yaml
      - !include /config/dashboards/420-pv/cards/420-pv-energy-flow-card.yaml
    layout:
      grid-template-columns: 365px 920px 365px
      margin: 0px;
      padding: 0px;
```

```
type: custom:energy-flow-card-plus
title: Energy Flows (Today)
min_flow_rate: 3
max_flow_rate: 10
wh_kwh_threshold: 0
kwh_decimals: 2
wh_decimals: 2
energy_date_selection: false
clickable_entities: true
entities:
  home:
    entity: sensor.house_consumption_energy_daily
    override_state: false
  solar:
    entity: sensor.solar_yield_daily
  battery:
    entity:
      consumption: sensor.battery_day_discharge_with_loss
      production: sensor.battery_day_charge_with_loss
    state_of_charge: sensor.battery_state_of_capacity
    color_circle: true
  grid:
    entity:
      consumption: sensor.power_meter_consumption_energy_daily
      production: sensor.power_meter_exported_energy_daily
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Low-carbon
    state_type: kWh
    show: true
card_mod:
  class: power-energy-flow-card
```
