### ISSUE TITLE
[BUG] When using override_stat flow is incorrect

### ISSUE THREAD

**Issue by nicx** [flixlix/power-flow-card-plus#282]
**Describe the bug**
When using override_state the flow is not correctly. The flow reflects still the state without override_state set. So in my example Without the override_state flag set I have a house consumption of 4.8kW, the flow is correct. When the flag is set, I have a house consumption of 1.3kW. The flow does not change, it's incorrect: there is a dot flowting from the battery to the house, even though the battery is charging. there should be a dot floating from solar to battery.

**To Reproduce**
1. Activate "override_state" for house consumption
2. look at the flow dots

**Expected behavior**
The flow dots are reflecting power consumption correctly when override_stat is set

**Screenshots**
<img width="470" alt="Bildschirmfoto 2023-06-15 um 07 42 37" src="https://github.com/flixlix/power-flow-card-plus/assets/25152397/b73b0948-b3e5-4c48-91d6-e77e6bfaabfc">

**Configuration YAML**
```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_charge_discharge_power
    state_of_charge: sensor.battery_state_of_capacity
  grid:
    entity:
      consumption: sensor.grid_consumption
      production: sensor.generation_to_grid
    invert_state: false
    use_metadata: false
  solar:
    entity: sensor.inverter_input_power
    display_zero_state: true
  home:
    entity: sensor.house_consumption
    use_metadata: false
    subtract_individual: false
    override_state: true
    secondary_info: {}
  individual1:
    entity: sensor.stellplatz_tesla_power
    calculate_flow_rate: false
    display_zero: true
    display_zero_state: true
    icon: mdi:car
    name: Stellplatz
  individual2:
    entity: sensor.garage_opel_power
    display_zero: true
    display_zero_state: true
    name: Garage
    icon: mdi:car
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
min_expected_power: 0.01
watt_threshold: 1000
max_expected_power: 15000

```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.
