### ISSUE TITLE
Lines dont always show the right direction[BUG]

### ISSUE THREAD

**Issue by gajotnt** [flixlix/power-flow-card-plus#289]
**Describe the bug**
Sometimes it works well, meaning the card knows were the energy is going (ex: solar to grid and solar to house)
Other times for example it show solar to grid and batery to grid, even if batery is at 0watts

**To Reproduce**

YAML:

```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_power
    use_metadata: false
    state_of_charge: sensor.battery_state_of_charge
    invert_state: false
  grid:
    entity: sensor.shellyem_34945473ec5d_channel_1_power
    secondary_info: {}
    invert_state: false
    use_metadata: false
  solar:
    entity: sensor.solar_energy_power
    display_zero_state: true
    secondary_info:
      entity: sensor.pv_power
    display_zero_tolerance: 4
  home:
    secondary_info:
      template: ''
      display_zero: true
      color_value: false
      unit_white_space: false
      icon: mdi:car-electric
      entity: sensor.duosida_power
    override_state: true
    subtract_individual: false
    entity: sensor.shellyem_34945473ec5d_channel_2_power
    use_metadata: false
  individual1:
    entity: sensor.powapart_energy_power
    name: Apartamento
    icon: mdi:home-clock
    calculate_flow_rate: true
    show_direction: false
    inverted_animation: false
  individual2:
    entity: sensor.pzemzoe_energy_power
    name: Cozinha
    inverted_animation: false
    display_zero_state: false
    display_zero: false
    color_icon: false
    icon: mdi:countertop
    show_direction: false
    use_metadata: false
    calculate_flow_rate: true
clickable_entities: false
display_zero_lines:
  mode: hide
  transparency: 75
  grey_color:
    - 66
    - 66
    - 66
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
min_expected_power: 1
watt_threshold: 1000
dashboard_link: ''
max_expected_power: 6900
```

**Expected behavior**
Like i said sometimes it works well, maybe someting to do with the values

**Screenshots**
Not working as intended:
https://github.com/flixlix/power-flow-card-plus/assets/25504364/7a104d18-a7fe-45fc-9ef9-19cb18dd6976

Working well:
https://github.com/flixlix/power-flow-card-plus/assets/25504364/472ecd28-b0db-444b-8ad6-2172cae3035a

Working well:
https://github.com/flixlix/power-flow-card-plus/assets/25504364/c17b0a31-3a0d-427b-8bd9-684d5990e704

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Oneplus Nord2
 - OS: Android 13
 - Browser HA APP
 - Version latest

**Please make sure all of this applies an

d check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.
