### ISSUE TITLE
[BUG] No flow line from grid to battery

### ISSUE THREAD

**Issue by steelixb** [flixlix/power-flow-card-plus#320]
The flow line is not visible when grid is charging the battery, despite displayed power values being correct.

It appears the grid to home flow line is still including battery.

![Screenshot_20230712_233309_Home Assistant](https://github.com/flixlix/power-flow-card-plus/assets/23078066/04bd79a2-b99c-4729-8b7e-6ed68a0b09a3)

Config:
```yaml
type: custom:power-flow-card-plus
use_new_flow_rate_model: true
entities:
  grid:
    entity: sensor.grid_import_power
    display_state: one_way
    color_circle: true
    display_zero_tolerance: 25
  battery:
    entity: sensor.battery_power
    display_state: one_way
    color_circle: true
    display_zero_tolerance: 25
  home:
    entity: sensor.consumption_power
    override_state: true
  individual1:
    entity: sensor.hypervolt_session_power
    icon: mdi:car-electric
    name: Car
    display_state: one_way
    color_circle: true
    display_zero: true
watt_threshold: 1000
w_decimals: 0
kw_decimals: 2
max_expected_power: 10000
display_zero_lines:
  mode: custom
  transparency: 70
  grey_color:
    - 127
    - 127
    - 127
```
