### ISSUE TITLE
no decimals in the secondary info in "individual1" [BUG]

### ISSUE THREAD

**Issue by cpohli** [flixlix/power-flow-card-plus#332]
**Describe the bug**
The "individual1" (indivudal2 not tested) does not show decimals in the secondary info.
Despite configured via "decimals: 1" or "decimals: 2". Always 0 decimals are shown.

**To Reproduce**
```
          individual1:
            entity: sensor.sma_wallbox_aktuell_kw
            icon: mdi:car-electric
            color: '#80b8ff'
            name: Wallbox
            color_icon: false
            secondary_info:
              entity: sensor.sma_wallbox_daily_kwh
              unit_of_measurement: "kWh"
              decimals: 1
            display_zero: true
```
If i copy the secondary info to on of the others (solar or home etc. it is displayed correctly.

**Expected behavior**
Show rounded value with 1 decimal

**Screenshots**
in the attached screenshot i copied the secondary sensor from "solar" to "wallbox".
Both are configued as:
```
            secondary_info:
              entity: sensor.solar_daily_kwh
              unit_of_measurement: "kWh"
              decimals: 1
```

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.
<img width="304" alt="SCR-20230725-jzcz" src="https://github.com/flixlix/power-flow-card-plus/assets/32699124/7b05c427-d68c-4737-a02b-4d033a84705d">
