### ISSUE TITLE
Battery Production / Consumpsion issue with flows

### ISSUE THREAD

**Issue by tomcoleman** [flixlix/power-flow-card-plus#35]
I have the battery code set as the following..

`
            type: custom:power-flow-card-plus
            entities:
              grid:
                entity:
                  consumption: sensor.solax_grid_import
                  production: sensor.solax_grid_export
              solar:
                entity: sensor.solax_pv_power_total
              battery:
                entity:
                   consumption: sensor.solax_battery_power_charge
                   production: sensor.solax_battery_power_charge
                state_of_charge: sensor.solax_battery_capacity

`

In this example battery consumption: sensor.solax_battery_power_charge and battery production:  sensor.solax_battery_power_charge are the same value.

My Solax battery does not show the real time in/out the sensor just shows realtime usage which at the time can be + or - 

So if i use the above code for the batts it screws with the flow of the balls & maths.

**Comment by flixlix** [comment]
From the readme:
![image](https://user-images.githubusercontent.com/61006057/228206906-aacebd96-9dca-4f77-9629-1e3d7d3cd404.png)

**Comment by tomcoleman** [comment]
so using the above what would the code be for

entity:
consumption: sensor.solax_battery_power_charge
production: sensor.solax_battery_power_charge
state_of_charge: sensor.solax_battery_capacity

**Comment by flixlix** [comment]
It would look like this:

[...]

```yaml
battery:
  entity: sensor.solax_battery_power_charge
  state_of_charger: sensor.solax_battery_capacity
```

[...]

And in case the values for the battery are going in the opposite way:

[...]

```yaml
battery:
  entity: sensor.solax_battery_power_charge
  state_of_charger: sensor.solax_battery_capacity
inverted_entities: battery
```

[...]

**Comment by flixlix** [comment]
you forgot to put the entity id next to the `entity:` property. Try this:

```yaml
            type: custom:power-flow-card-plus
            entities:
              grid:
                entity:
                  consumption: sensor.solax_grid_import
                  production: sensor.solax_grid_export
              solar:
                entity: sensor.solax_pv_power_total
              battery:
                entity: sensor.solax_battery_power_charge
                state_of_charge: sensor.solax_battery_capacity
```

**Comment by tomcoleman** [comment]
> 

ok put that in and now shows house load as 0 and balls flying from solar > batt  ( which isnt right)

![image](https://user-images.githubusercontent.com/1098848/228228934-9c9bc9aa-c9ec-486f-bb96-bff3d702e6fb.png)

**Comment by tomcoleman** [comment]
ignore that got it working
![image](https://user-images.githubusercontent.com/1098848/228235199-73834659-4973-4189-8b51-8d693becd48f.png)

how ever when i add the BMW i3 in it thinks its charging it

![image](https://user-images.githubusercontent.com/1098848/228235329-ca58e4be-c47d-4ac9-b8d1-87f2e037f220.png)

entity: sensor.i3_120_remaining_battery_percent

**Comment by flixlix** [comment]
Please read the readme, it's right there.
https://github.com/flixlix/power-flow-card-plus#secondary-info-configuration
The entity providing the battery percentag should be in secondary_info.
The Main entity is the power of the individual device

**Comment by tomcoleman** [comment]
> Please read the readme, it's right there. https://github.com/flixlix/power-flow-card-plus#secondary-info-configuration The entity providing the battery percentag should be in secondary_info. The Main entity is the power of the individual device

THANK YOU!!

me being a muppet i have put the % sign on it but it still thinks energy is going into the car with the blue ball going from house to car

![image](https://user-images.githubusercontent.com/1098848/228239297-c04f2b87-1483-462d-9350-ec520e3f0d40.png)

**Comment by flixlix** [comment]
You can't have two `entity` properties. Please try this:

```yaml

              individual1:
                entity: sensor.myenergi_zappi_20197616_internal_load_ct1
                secondary_info:
                  entity: sensor.i3_120_remaining_battery_percent
                  unit_of_measurement: "%"
                icon: mdi:car-electric
                color: '#80b8ff'
                name: BMW i3
                color_icon: false
```

**Comment by tomcoleman** [comment]
> You can't have two `entity` properties. Please try this:
> 
> ```yaml
>               individual1:
>                 entity: sensor.myenergi_zappi_20197616_internal_load_ct1
>                 secondary_info:
>                   entity: sensor.i3_120_remaining_battery_percent
>                   unit_of_measurement: "%"
>                 icon: mdi:car-electric
>                 color: '#80b8ff'
>                 name: BMW i3
>                 color_icon: false

![image](https://user-images.githubusercontent.com/1098848/228248050-a5bd693b-e994-411f-a16e-d75b7ea7087b.png)


that code makes the icon disapear

**Comment by flixlix** [comment]
Please read the documentation, you would save both of us time.

```yaml

              individual1:
                entity: sensor.myenergi_zappi_20197616_internal_load_ct1
                secondary_info:
                  entity: sensor.i3_120_remaining_battery_percent
                  unit_of_measurement: "%"
                icon: mdi:car-electric
                color: '#80b8ff'
                name: BMW i3
                color_icon: false
                display_zero: true
```

The icon is not appearing, because your car isn't charging. Set `display_zero` to `true` to always show the device
