### ISSUE TITLE
UI not provided: ERROR

### ISSUE THREAD

**Issue by maijo366** [flixlix/power-flow-card-plus#359]
Please help:

UI not provided: ERROR

    s.entries is not a function

Du kannst deine Konfiguration weiterhin in YAML bearbeiten.

This is my code:
```
type: custom:power-flow-card-plus
entities:
  individual1: 
    name: Skoda Enyaq
    entity: sensor.skoda_enyaq_ladeenergie_monatlich_kwh_charging
  individual2:
    entity: sensor.taglich_3
    name: Wasser
    unit_of_measurement: L
    icon: mdi:water
  battery:
    entity: ''
    name: iPhone 12
    state_of_charge: sensor.iphone_12pro_joe_battery_level
    display_state: two_way
  grid:
    entity:
      consumption: sensor.smart_meter_ts_65a_3_energy_real_consumed
      production: sensor.smart_meter_ts_65a_3_energy_real_produced
    display_state: two_way
    color_circle: true
  solar:
    entity: sensor.pv_fronius_gen24_8_0_energy_total
    display_zero_state: true
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 1
kw_decimals: 0
min_flow_rate: 0.75
max_flow_rate: 4
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 50

```
