### ISSUE TITLE
[SUPPORT] Individual entities not working as expected

### ISSUE THREAD

**Issue by andiweli** [flixlix/power-flow-card-plus#383]
I want to show a power usage of a computer as "individual1" or "individual2" icon - but it isn't shown.

I used the code from GitHub with my sensor for the power usage of the computer:

  individual1:
    entity: sensor.computer_power
    name: Computer
    icon: mdi:desktop-classic
    display_zero: true

![Screenshot 2023-09-16 023243](https://github.com/flixlix/power-flow-card-plus/assets/11447150/5b370a27-dd87-4195-bcb2-3b42f4ac53da)

The device is currently using 300 watts...
What's wrong with my configuration?
Thanks.

**Comment by flixlix** [comment]
Hey,
can you please share your whole config for the card as well as the version that is being shown in the console?

**Comment by andiweli** [comment]
I've installed 0.1.8.1

The config is as follows...

```
type: custom:power-flow-card-plus
use_new_flow_rate_model: true
watt_threshold: 1000
min_flow_rate: 1
max_flow_rate: 5
display_zero_lines:
  mode: hide
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
entities:
  home:
    entity: sensor.Stromverbrauch_Gesamt
    color: '#4599DF'
    color_icon: true
  grid:
    entity: sensor.Stromverbrauch_Netzbezug
    display_state: one_way
    color:
      production: '#4599DF'
      consumption: '#4599DF'
    color_value: false
    color_circle: true
    color_icon: true
  solar:
    entity: sensor.Wechselrichter_HMmitZendure
    color: '#F2AA3C'
    color_icon: true
  battery:
    entity:
      consumption: sensor.SolarFlow_StromausgangAkku
      production: sensor.SolarFlow_LadevorgangAkku
    state_of_charge: sensor.SolarFlow_Akkuladung
    display_state: one_way
    color:
      consumption: '#5C9D51'
      production: '#5C9D51'
    color_value: false
    color_circle: true
    color_icon: true
  individual2:
    entity: sensor.Verteiler_3er_Lukas_Computer_POWER
    name: Gaming PC
    color_icon: true
    display_zero: true
    icon: mdi:desktop-classic
```

**Comment by andiweli** [comment]
Funny thing, if I only exchange "individial2" to "fossil_fuel_percentage" I get this... 

![image](https://github.com/flixlix/power-flow-card-plus/assets/11447150/98975a9e-b419-49e1-a116-81484135fb04)

**Comment by flixlix** [comment]
Maybe I figured it out.
Are your entities states negative? The card does not accept that, can you try supplying the individual1 with your solar entity?

**Comment by andiweli** [comment]
Hmm, no they are all positive...
![image](https://github.com/flixlix/power-flow-card-plus/assets/11447150/d03af3e8-bc50-4498-b0fc-cddd0b0ed68e)

I already tried a few other values, here with the solar entity...
![image](https://github.com/flixlix/power-flow-card-plus/assets/11447150/278de918-869f-4015-861f-a11f45f79ee6)

Sidenote: I am running on ioBroker and using Lovelace. So far every card I tried worked without problems. I don't hope that could be an issue...

**Comment by flixlix** [comment]
This is very weird indeed...

Just to make sure, what version of the card is shown in the browser console?

**Comment by OArndt** [comment]
Similar problem here.
Can't see "individual1".
Just installed this card. Version 0.1.8.1 is installed.
Here is my code:


```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.scb_home_power_from_battery
    state_of_charge: sensor.scb_battery_soc
  grid:
    entity: sensor.scb_grid_power
  solar:
    entity: sensor.scb_solar_power
    display_zero_state: true
  individual1:
    entity: sensor.keba_p30_charging_power
    icon: mdi_car-electric
    name: Wallbox
    unit_of_measurement: kW
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: null
kw_decimals: 2
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0

```

**Comment by HerrKlaus** [comment]
Same issue here when using the card within Lovelace on ioBroker.
Used card version is 0.1.8.1, used version of home-assistant-frontend@20230906.1, version of Browser Mod: 2.3.0
I can confirm the feedback from @andiweli [a few lines above](https://github.com/flixlix/power-flow-card-plus/issues/383#issuecomment-1724322730). "individial1" or "individial2" is not shown, but if I change the entity to "fossil_fuel_percentage" it works.
@flixlix: I saw in the cards source code that the individual1 and 2 part is defined a little bit different than all the "main" entities. Looks like using arrays or structures for the 1 and 2 to avoid double maintenance. Maybe this causes the trouble in our environment. Any advice for debugging?

**Comment by andiweli** [comment]
fossil_fuel_percentage also works for me, but that's not what individual1 + 2 is meant for.
fossil_fuel_percentage is production, individual1 + 2 are consumption.

**Comment by flixlix** [comment]
I'm not sure what might be going wrong here, maybe the card has some conflicts with iobroker... I can't check if this is compatible since I don't have any iobroker installation...

**Comment by RALFISBORN** [comment]
Same Problem here with IOBroker:

Apart from the problem with individual1 and 2.
I also have the problem that the value for fossil_fuel_percentage is not displayed:
![image](https://github.com/flixlix/power-flow-card-plus/assets/47441243/04d83730-3a7a-46f9-a2d2-4ebea9a969c9)

![image](https://github.com/flixlix/power-flow-card-plus/assets/47441243/94081341-dc33-4fba-b1f9-77280be6c05f)

YAML:
```
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.Elektro_Bezug
      production: sensor.Elektro_Einspeisung
      display_state: two_way
      color_circle: true
  solar:
    entity: sensor.Elektro_Solar
    name: DachPV
  home:
    entity: sensor.Elektro_Statistik_Verbrauch
    name: Homebase
    override_state: true
  battery:
    name: Battery
    icon: mdi:bat
    entity:
      consumption: sensor.battery_consumption
      production: sensor.battery_production
  fossil_fuel_percentage:
    entity: sensor.Elektro_Solar2
    name: PV2
    color_icon: true
    display_zero: true
    color: '#ff8080'
    icon: mdi:motorbike-electric
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 3
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
title: Aktueller elektrischer Verbrauch
```
