### ISSUE TITLE
Non-fossil doesn't show on the Home node

### ISSUE THREAD

**Issue by ssorgatem** [flixlix/power-flow-card-plus#39]
This is probably related to https://github.com/flixlix/power-flow-card-plus/issues/24 in some way.

Here's my config
```
title: Energia a temps real
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.power_meter_active_power
  solar:
    entity: sensor.inverter_active_power
  individual1:
    entity: sensor.regleta_tl_power
    name: Ordinador
    icon: mdi:monitor
    color: '#ff0000'
    display_zero: true
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    color_icon: true
    display_zero: true
    state_type: power
inverted_entities: grid
w_decimals: 0
kw_decimals: 2
clickable_entities: true
watt_threshold: 10000
```
And it looks like this:
![image](https://user-images.githubusercontent.com/108138/228461018-e243ef8f-19dd-4048-964a-69af18ce130d.png)

I would expect the home node to be part yellow, part blue, and part green, with more green than blue, just like with the energy panel card, but there's no green to be seen.

Since there is green in the example card in the readme, I guess this is a bug.
