### ISSUE TITLE
[SUPPORT] Assistance needed to adapt Tesla Powerwall sensors to required entities for power-flow-card-plus 

### ISSUE THREAD

**Issue by mkanet** [flixlix/power-flow-card-plus#420]
I currently use the [Tesla powerwall integration](https://www.home-assistant.io/integrations/powerwall/) as the primary source for https://github.com/reptilex/tesla-style-solar-power-card . This card's documentation provided **full template sensor code needed to make the card work (presuming I have the use has the [Tesla powerwall integration](https://www.home-assistant.io/integrations/powerwall/))**.

Unfortunately, I don't see similar documentation/template code that I can also use for the **power-flow-card-plus** card (presuming I have a [Tesla powerwall integration](https://www.home-assistant.io/integrations/powerwall/)). Obivously, Power Flow Card Plus will not work without providing all the required template sensors that use the Tesla Powerwall integration source sensors and any respective helper sensors.

Below are all my current sensors for the [telsa-style-solar-power-card](https://github.com/reptilex/tesla-style-solar-power-card). I need the respective similar sensors needed to fully take advantage of the source sensors from [Tesla powerwall integration](https://www.home-assistant.io/integrations/powerwall/) in Power-flow-card-plus.

```yaml
      # Tesla Powerwall custom card support:
      - name: APF Grid Entity
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: "{{ ((0 - states('sensor.powerwall_site_power')|float * 1000) / 100)|round(0) * 100 }}"
      - name: APF House Entity
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: "{{ (states('sensor.powerwall_load_power')|float * 1000 / 100)|round(0) * 100 }}"
      - name: APF Generation Entity
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: "{{ (states('sensor.powerwall_solar_power')|float * 1000 / 100)|round(0) * 100 }}"
      - name: APF Battery Entity
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: "{{ ((0 - states('sensor.powerwall_battery_power')|float * 1000) / 100)|round(0) * 100 }}"
      - name: APF Grid Import
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_grid_entity')|int(default=0) < 0 %}
            {{ states('sensor.apf_grid_entity')|int(default=0)|abs }}
          {% else %}
            0
          {% endif %}
      - name: APF Inverter Power Consumption
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: "{{ states('sensor.apf_generation_entity')|int(default=0) - states('sensor.apf_battery_entity')|int(default=0) - states('sensor.apf_house_entity')|int(default=0) - states('sensor.apf_grid_entity')|int(default=0) }}"
      - name: APF Real House Load
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: "{{ states('sensor.apf_house_entity')|int(default=0) + states('sensor.apf_inverter_power_consumption')|int(default=0) }}"
        icon: mdi:home-lightning-bolt
      - name: APF Grid2House
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state:  >
          {% if states('sensor.apf_grid_import')|int(default=0) > states('sensor.apf_real_house_load')|int(default=0) %}
            {{ states('sensor.apf_real_house_load')|int(default=0) }}
          {% else %}
            {{ states('sensor.apf_grid_import')|int(default=0) }}
          {% endif %}
      - name: APF Grid2Batt
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_grid_import')|int(default=0) > states('sensor.apf_real_house_load')|int(default=0) %}
            {{ states('sensor.apf_grid_import')|int(default=0) - states('sensor.apf_real_house_load')|int(default=0) }}
          {% else %}
            0
          {% endif %}
      - name: APF Batt2House
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_battery_entity')|int(default=0) < 0 %}
            {% if states('sensor.apf_battery_entity')|int(default=0)|abs > states('sensor.apf_real_house_load')|int(default=0) %}
              {{ states('sensor.apf_real_house_load')|int(default=0) }}
            {% else %}
              {{ states('sensor.apf_battery_entity')|int(default=0)|abs }}
            {% endif %}
          {% else %}
            0
          {% endif %}
      - name: APF Batt2Grid
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_battery_entity')|int(default=0) < 0 %}
            {% if states('sensor.apf_battery_entity')|int(default=0)|abs > states('sensor.apf_real_house_load')|int(default=0) %}
              {{ states('sensor.apf_battery_entity')|int(default=0)|abs - states('sensor.apf_real_house_load')|int(default=0) }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
      - name: APF Solar2Grid
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_grid_entity')|int(default=0) > states('sensor.apf_batt2grid')|int(default=0) %}
            {{ states('sensor.apf_grid_entity')|int(default=0) - states('sensor.apf_batt2grid')|int(default=0) }}
          {% else %}
            0
          {% endif %}
      - name: APF Solar2House
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_generation_entity')|int(default=0) > 0 and states('sensor.apf_real_house_load')|int(default=0) > states('sensor.apf_batt2house')|int(default=0) + states('sensor.apf_grid_import')|int(default=0) %}
            {% if states('sensor.apf_generation_entity')|int(default=0) > states('sensor.apf_real_house_load')|int(default=0) - states('sensor.apf_batt2house')|int(default=0) - states('sensor.apf_grid2house')|int(default=0) %}
              {{ states('sensor.apf_real_house_load')|int(default=0) - states('sensor.apf_batt2house')|int(default=0) - states('sensor.apf_grid2house')|int(default=0) }}
            {% else %}
              {{ states('sensor.apf_generation_entity')|int(default=0) }}
            {% endif %}
          {% else %}
            0
          {% endif %}
      - name: APF Solar2Batt
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        state: >
          {% if states('sensor.apf_generation_entity')|int(default=0) > 0 and states('sensor.apf_battery_entity')|int(default=0) > 0 %}
            {% if states('sensor.apf_battery_entity')|int(default=0) > states('sensor.apf_grid2batt')|int(default=0) %}
              {% if states('sensor.apf_generation_entity')|int(default=0) - states('sensor.apf_solar2house')|int(default=0) > states('sensor.apf_battery_entity')|int(default=0) - states('sensor.apf_grid2batt')|int(default=0) %}
                {{ states('sensor.apf_battery_entity')|int(default=0) - states('sensor.apf_grid2batt')|int(default=0) }}
              {% else %}
                {{ states('sensor.apf_generation_entity')|int(default=0) - states('sensor.apf_solar2house')|int(default=0) - states('sensor.apf_solar2grid')|int(default=0) }}
              {% endif %}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
```

**Comment by mkanet** [comment]
I was able to to figure this out:  

```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.apf_grid2house
      production: sensor.apf_batt2grid
    display_state: one_way
    color_circle: true
  solar:
    entity: sensor.apf_solar2grid
    secondary_info: sensor.openweathermap_cloud_coverage
  battery:
    entity:
      consumption: sensor.apf_batt2house
      production: sensor.apf_solar2batt
    state_of_charge: sensor.mka_net_charge
    display_state: one_way
    color_circle: true
  home:
    color_icon: true
watt_threshold: 800
w_decimals: 1
min_flow_rate: 3.5
max_flow_rate: 6
```
