### ISSUE TITLE
[BUG]  display_zero_lines completely ignored

### ISSUE THREAD

**Issue by mkanet** [flixlix/power-flow-card-plus#421]
**Describe the bug**
Every single line possible is displayed even when there is no activity between circles when I have enabled:
```
    display_zero_lines:
      mode: hide
```
The card is too confusing with all these lines permanently displayed.
![image](https://github.com/flixlix/power-flow-card-plus/assets/811008/a4c0f342-c0f3-43e2-9561-94697af5da46)

I have installed the latest version from HACS.  **v0.1.8.1**  
None of the respective modes `hide`, `transparency`, etc don't work.  I am pretty sure I'm using it the way it was intended as described in the readme.md

My card code is:
```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.apf_grid2house
      production: sensor.apf_batt2grid
    display_state: one_way
    color_circle: true
    display_zero_lines:
      mode: hide
  solar:
    entity: sensor.apf_solar2grid
    secondary_info: sensor.openweathermap_cloud_coverage
    display_zero_lines:
      mode: hide
  battery:
    entity:
      consumption: sensor.apf_batt2house
      production: sensor.apf_solar2batt
    state_of_charge: sensor.mka_net_charge
    display_state: one_way
    color_circle: true
    display_zero_lines:
      mode: hide
  home:
    color_icon: true
    display_zero_lines:
      mode: hide
watt_threshold: 800
w_decimals: 1
min_flow_rate: 3.5
max_flow_rate: 6
use_new_flow_rate_model: true
```

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
Your config is incorrect. It should look like this:

```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.apf_grid2house
      production: sensor.apf_batt2grid
    display_state: one_way
    color_circle: true
  solar:
    entity: sensor.apf_solar2grid
    secondary_info:
      entity: sensor.openweathermap_cloud_coverage

  battery:
    entity:
      consumption: sensor.apf_batt2house
      production: sensor.apf_solar2batt
    state_of_charge: sensor.mka_net_charge
    display_state: one_way
    color_circle: true

  home:
    color_icon: true

watt_threshold: 800
w_decimals: 1
min_flow_rate: 3.5
max_flow_rate: 6
use_new_flow_rate_model: true
display_zero_lines:
   mode: hide
```

The display zero lines is applied at base level for all lines
