### ISSUE TITLE
[SUPPORT] Help with minor style change to labels

### ISSUE THREAD

**Issue by mkanet** [flixlix/power-flow-card-plus#423]
Thank you so much for all your help.  I have learned as much as I can from the documentation.  However, I need a little help to modify the styles for the labels below.  **I think other users would also be able to benefit from from modifications below.**

During a power outage, the Grid circle will look like below.  How can I change the **Power Outage** text color to be in **red** color?  It appears the only way to do it is via `style_card_content` card option.  Could you please 🙏🙏🙏 show me how to do this? 
![image](https://github.com/flixlix/power-flow-card-plus/assets/811008/6b7181a6-bd5c-4aee-8714-83de1edd151c)

Also, how do I change the text labels `Grid` `Battery` `Home` `Solar` to be a **bold** font in the same fashion as above?  Once I know how to do this, optionally, I can also make the respective font size a little bigger too for these labels.
![image](https://github.com/flixlix/power-flow-card-plus/assets/811008/3e8179d7-7170-4808-9707-ac6df4301e6d)

Below, is my current card config:

```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.mka_net_site_power
    secondary_info:
      entity: sensor.pge_electric_cost_to_date
      unit_of_measurement: $
      unit_white_space: false
      color_value: true
    display_state: one_way
    color_circle: true
    color_icon: true
    color_value: true
    power_outage:
      entity: binary_sensor.mka_net_grid_status
      state_alert: 'off'
  solar:
    entity: sensor.mka_net_solar_power
    icon: mdi:solar-panel-large
    secondary_info:
      entity: sensor.openweathermap_cloud_coverage
      unit_of_measurement: '%'
      unit_white_space: false
      color_value: true
    color_icon: true
    color_value: true
  battery:
    entity: sensor.mka_net_battery_power
    state_of_charge: sensor.mka_net_charge
    state_of_charge_unit: '%'
    state_of_charge_unit_white_space: false
    display_state: one_way
    color_state_of_charge_value: true
    color_icon: true
    color_circle: true
  home:
    entity: sensor.mka_net_load_power
    color_icon: true
    color_value: true
watt_threshold: 999
calculate_flow_rate: true
w_decimals: 1
kw_decimals: 1
max_flow_rate: 10
display_zero_lines:
  mode: hide
clickable_entities: true
```

**Comment by mkanet** [comment]
I figured it out!  Below, will make the outage text color red.  I can do the same thing for the other elements.

```yaml
    style_card_content: |
      .circle {
        color: #FF516E;
      }
```

**Comment by mkanet** [comment]
Here is a more targetted CSS rule below; which also doesn't work.
```yaml
style_card_content: |
  .circle-container .grid.power-outage {
    color: Red;
  }
```
