### ISSUE TITLE
[SUPPORT] Not sure how `display_state` is supposed to work and animation direction and animation direction

### ISSUE THREAD

**Issue by tomayac** [flixlix/power-flow-card-plus#425]
Thanks for this amazing card! I use it with the [Enphase Envoy integration](https://www.home-assistant.io/integrations/enphase_envoy/)! First, I know from my [own project](https://github.com/tomayac/enphase-solar) that the production/consumption numbers I can see in the card all add up; it's all correct.

But I have some doubts about how `display_state` is supposed to work and the animation direction. Here's my configuration:

```yaml
- type: custom:power-flow-card-plus
  entities:
    grid:
      entity:
        consumption: sensor.envoy_122232075621_current_power_consumption
        production: sensor.envoy_122232075621_current_power_production
      invert_state: false
      display_state: two_way
    solar:
      entity: sensor.envoy_122232075621_current_power_production
      display_zero_state: true
    home:
      entity: sensor.envoy_122232075621_current_power_consumption
  clickable_entities: true
  display_zero_lines:
    mode: show
    transparency: 50
    grey_color:
      - 189
      - 189
      - 189
  use_new_flow_rate_model: true
  w_decimals: 0
  kw_decimals: 2
  min_flow_rate: 0.75
  max_flow_rate: 6
  max_expected_power: 10000
  min_expected_power: 0.01
  watt_threshold: 1000
  transparency_zero_lines: 0
  title: Current power flow
```

In this case, `two_way` works as intended. Note, though, how **Solar** feeds into **Grid** according to the animation, when intuitively it should fully feed into **Home** (I'm importing more than I'm producing, but what I'm producing I'm fully consuming). I would thus rather expect an orange dot going from **Solar** to **Home**.

![Screenshot 2023-11-09 at 11 30 20](https://github.com/flixlix/power-flow-card-plus/assets/145676/1cf8cb6b-537e-4414-b489-306db52704e1)

If I change the `display_mode` to `one_way`, which I think is a more intuitive way of showing what's going on, nothing shows under **Grid**.

```yaml
- type: custom:power-flow-card-plus
  entities:
    grid:
      entity:
        consumption: sensor.envoy_122232075621_current_power_consumption
        production: sensor.envoy_122232075621_current_power_production
      invert_state: false
      display_state: one_way
    solar:
      entity: sensor.envoy_122232075621_current_power_production
      display_zero_state: true
    home:
      entity: sensor.envoy_122232075621_current_power_consumption
  clickable_entities: true
  display_zero_lines:
    mode: show
    transparency: 50
    grey_color:
      - 189
      - 189
      - 189
  use_new_flow_rate_model: true
  w_decimals: 0
  kw_decimals: 2
  min_flow_rate: 0.75
  max_flow_rate: 6
  max_expected_power: 10000
  min_expected_power: 0.01
  watt_threshold: 1000
  transparency_zero_lines: 0
  title: Current power flow
```

![Screenshot 2023-11-09 at 11 34 13](https://github.com/flixlix/power-flow-card-plus/assets/145676/7f069c38-0b9f-4dcd-9937-05df4ce12a57)

For comparison, here's a screenshot from my own monitor:

![Screenshot 2023-11-09 at 11 40 24](https://github.com/flixlix/power-flow-card-plus/assets/145676/8327dc38-122f-4a64-944c-696607d0e91a)

And here's a screenshot from the official Enphase Enlighten app:

![image](https://github.com/flixlix/power-flow-card-plus/assets/145676/8d3789e7-5353-43e7-aca7-436bcc9a5f84)

Thank you very much for the card again. Hope you can point me at the thing I do wrong with `display_state` and that maybe the feedback about the animation direction is useful.

**Comment by flixlix** [comment]
The issue might be that your two grid sensors are reporting numbers above 0, both consumption and production. This is impossible in real life, power can only flow in one direction, so the card only supports this use case. Can you try removing one of the entities from grid and see what happens.

When `display_state` is set to `one_way`, you will only see the current direction of flow, that might be conflicting with your setup currently

**Comment by tomayac** [comment]
Thanks for getting back! Here the two tests (always comparing the Power Flow Card Plus below with my own widget that correspond to the data I get from the official Enphase app above):

1. Grid only consumption means I lose information about the fact that I'm exporting:

   ```yaml
              grid:
                entity:
                  consumption: sensor.envoy_122232075621_current_power_consumption
                invert_state: false
                display_state: one_way
              solar:
                entity: sensor.envoy_122232075621_current_power_production
                display_zero_state: true
              home:
                entity: sensor.envoy_122232075621_current_power_consumption
   ```

   ![Screenshot 2023-12-08 at 11 09 56](https://github.com/flixlix/power-flow-card-plus/assets/145676/759f5222-d89c-4880-8343-52b56522010b)

1. Grid only production means the numbers are completely wrong:

   ```yaml
              grid:
                entity:
                  consumption: sensor.envoy_122232075621_current_power_production
                invert_state: false
                display_state: one_way
              solar:
                entity: sensor.envoy_122232075621_current_power_production
                display_zero_state: true
              home:
                entity: sensor.envoy_122232075621_current_power_consumption
   ```

   ![Screenshot 2023-12-08 at 11 14 26](https://github.com/flixlix/power-flow-card-plus/assets/145676/ae351687-b481-4daa-987f-8374c412870e)

**Comment by tomayac** [comment]
I guess what I want is

**Comment by flixlix** [comment]
Hey there, thank you for the screenshots.
The reason this is not working, is that it is not possible to import and export from the grid at the same time. Is it possible you are trying to show energy?

**Comment by tomayac** [comment]
> The reason this is not working, is that it is not possible to import and export from the grid at the same time.

Well, it _is_ possible, the [lower half of the screenshot](https://private-user-images.githubusercontent.com/145676/289041692-3cd3f35d-ffab-4bfb-b8b2-68f439156d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDc5OTYsIm5iZiI6MTcwNTMwNzY5NiwicGF0aCI6Ii8xNDU2NzYvMjg5MDQxNjkyLTNjZDNmMzVkLWZmYWItNGJmYi1iOGIyLTY4ZjQzOTE1NmQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwODM0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTQ5Yzg2M2Q5OTFhYjY0Y2VjNGU5NWYwMTZiZDE0NTYyYTUzMDc2MzNkMTg0ZmM3ZjAyN2QyZjY1ODVjMjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mHfu26CyVGolwTAzJ5aqah_KTdSKCzdV-kdKuOUblto) has all the data. All I'd wish for would be for the difference to be calculated and shown instead of the two individual stats. Do you think this makes sense?

**Comment by flixlix** [comment]
Maybe I'm missing something but power can definitely only flow in one direction at the time. You can't import and export at the same time. It's just not physically possible

**Comment by tomayac** [comment]
The configuration that works and that gives me the numbers in the screenshot is the one below:

```yaml
 grid:
  entity:
    consumption: sensor.envoy_122232075621_current_power_consumption
    production: sensor.envoy_122232075621_current_power_production
  invert_state: false
  display_state: two_way
solar:
  entity: sensor.envoy_122232075621_current_power_production
  display_zero_state: true
home:
  entity: sensor.envoy_122232075621_current_power_consumption
```
