### ISSUE TITLE
[FEATURE REQUEST] Please add multiple battery entity option

### ISSUE THREAD

**Issue by JakobTewes** [flixlix/power-flow-card-plus#426]
**Provide multiple Battery enities**
I have two separate battery storage systems. Would be great, having the change adding both

Thanks and regards

Jakob

**Comment by gcoan** [comment]
+1 from me.  I have two inverters, each with their own solar array and battery so would love to be able to see both on the same card and not have to have two cards (one for each inverter) and look between them

**Comment by matchermike1981** [comment]
+1 from me too please :-)

**Comment by Wovchik** [comment]
+1 have 2 different battery, too

**Comment by gcoan** [comment]
Have a look at https://github.com/flixlix/power-flow-card-plus/issues/512

I used the beta version of PF+ that allows up to 4 individual items and configured two of them as second battery and second solar array.  It works quite well as it stands, albeit with a few limitations (esp calc house load is wrong)

**Comment by Wovchik** [comment]
i cant get the same Values shown like the native battery with individual items

**Comment by gcoan** [comment]
> i cant get the same Values shown like the native battery with individual items

If you have a look at the yaml configuration I posted in the other issue,I was able to show the second battery SoC and power flow in & out.

As its not a proper battery object it doesn't show the flow direction arrow (but the moving dots are animated correctly) and it's a static battery icon but it's usable.

![image](https://github.com/flixlix/power-flow-card-plus/assets/142018870/d2bf1a01-a252-44b8-b072-0742e803d383)

**Comment by Wovchik** [comment]
not working here and i dont know why... 
![image](https://github.com/flixlix/power-flow-card-plus/assets/45832698/0cd51109-a34c-4474-bf7e-e9fdd0effe1c)
Names, symbols and secondary values ​​are not displayed as expected.

**Comment by Wovchik** [comment]
`type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.sn_3015659959_battery_power_charge_total
    state_of_charge: sensor.sn_3015659959_battery_soc_total
  grid:
    entity: sensor.sn_3015659959_grid_power
  solar:
    entity: sensor.sn_3015659959_pv_power
    display_zero_state: true
    secondary_info:
      entity: sensor.mein_haus_solar_energie
      icon: ''
      decimals: 2
      unit_of_measurement: kW
  individual:
    - entity: sensor.mein_haus_ladung
    - entity: sensor.smaev_3011748221_charging_station_power
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
`
newest beta and Config with gui and see now that YAML not realy contains this changes :-(

**Comment by gcoan** [comment]
its difficult to follow precisely as the yaml has lost all the indentation, but I can see that the individual items don't have any extra configuration other than the entity names.

```
  individual:
    - entity: sensor.mein_haus_ladung
      name: 
    - entity: sensor.smaev_3011748221_charging_station_power
```

Here's what I think the individual items should be configured like:
```
  individual:
    - entity: sensor.mein_haus_ladung
      name: Battery
      icon: mdi:battery
      display_zero: true
      secondary_info:
        entity: sensor.battery_percentage_soc
        unit_of_measurement: '%'
      inverted_animation: true
      display_zero_state: false
      calculate_flow_rate: true
      show_direction: true
    - entity: sensor.smaev_3011748221_charging_station_power
      name: Wallbox
      icon: mdi:car
      display_zero: true
      calculate_flow_rate: true
```

You'll need to put the right sensor name in for battery percentage.
