### ISSUE TITLE
[SUPPORT] Home is not showing correct values

### ISSUE THREAD

**Issue by abacao** [flixlix/power-flow-card-plus#427]
Hello all,

I'm currently using only one Shelly EM to have information about my installation.

Shelly EM main channel is looking at the power that is traveling from the grid to home or from home to grid (with an minus value).
Shelly EM 2 channel is looking only about the power solar is generating.

I'm having difficulties on having the "home" icon to display the correct data.

```
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.total_power #this is where i see the current home consumption
  solar:
    entity: sensor.main_shelly_em_channel_2_power #this is where i see the solar total power production

```

![image](https://github.com/flixlix/power-flow-card-plus/assets/17479246/109dae30-a44d-4289-a3c5-e65861c9ba6b)

![image](https://github.com/flixlix/power-flow-card-plus/assets/17479246/13d3a015-7398-4085-a841-ce8fa31efeaa)

What can I be doing wrong?
