### ISSUE TITLE
Spacing between icon and secondary_info entity on the Grid is smaller than other similar locations

### ISSUE THREAD

**Issue by jamespreedy** [flixlix/power-flow-card-plus#439]
Using Safari 17.1.2 on Mac OS 14.1.2 and iOS 17.1.2 on iPhone 15 Pro and iPhone 11 Pro.
Safari is not zoomed at all. Running v0.1.8.1 on HA 2023.12.0

This is a visual bug. The Spacing between the icon and the secondary_info entity on the Grid is smaller than other similar locations. This means that the text is partially obscured by the icon. This doesn't seem to be the same for individual1 and individual2.

Screenshot showing this below - green boxes seem ok, red box spacing issue described above.

![Screenshot 2023-12-08 at 7 57 45 am copy](https://github.com/flixlix/power-flow-card-plus/assets/559531/f134bf77-36d7-4c2c-b2b1-64bff19f1b44)

This is the same whether the consumption or production entities are shown (or hidden using display_zero_tolerance).

![Screenshot 2023-12-08 at 7 57 56 am](https://github.com/flixlix/power-flow-card-plus/assets/559531/fb5c9db1-4bf1-42f6-9ee6-80eaffa50c0a)

```
  - type: custom:power-flow-card-plus
    entities:
      grid:
        entity:
          consumption: sensor.grid_mains_import_power
          production: sensor.grid_mains_export_power
        display_state: one_way_no_zero
        color_circle: true
        display_zero_tolerance: 0
        color_value: false
        color_icon: true
        secondary_info:
          entity: sensor.grid_power_status
          unit_white_space: false
          color_value: false
      solar:
        entity: sensor.solax_pv_power_total
        display_zero_state: false
        display_zero_tolerance: 0
        color_value: false
        color_icon: true
      battery:
        entity:
          consumption: sensor.solax_battery_consumption
          production: sensor.solax_battery_production
        state_of_charge: sensor.solax_battery_capacity
        display_state: one_way
        color_circle: true
        color_value: false
        color_icon: true
      home:
        color_icon: true
        subtract_individual: true
        use_metadata: false
      individual1:
        name: MVHR
        icon: mdi:hvac
        display_zero_state: false
        display_zero: true
        color_icon: true
        entity: sensor.smart_meter_mvhr_power
        color_value: false
        display_zero_tolerance: 55
        color:
          - 148
          - 33
          - 146
        secondary_info:
          entity: sensor.mvhr_mode
          unit_white_space: true
      individual2:
        display_zero: true
        name: ASHP
        icon: mdi:heat-pump
        show_direction: false
        entity: sensor.smart_meter_ashp_power
        color_value: false
        color_icon: true
        color:
          - 148
          - 33
          - 146
        display_zero_tolerance: 55
        display_zero_state: false
        secondary_info:
          entity: sensor.ashp_mode
    watt_threshold: 0
    w_decimals: 1
    display_zero_lines:
      mode: grey_out
      transparency: 50
      grey_color:
        - 235
        - 235
        - 235
    clickable_entities: false
    use_new_flow_rate_model: true
```

If there's any more information I can get, or help troubleshoot this further, please let me know.
This is a great card - I really appreciate the time it took to build and support - thank you!!!

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.
