### ISSUE TITLE
[BUG] Solar `display_zero_tolerance` prevents Grid-->Battery flow line/animation

### ISSUE THREAD

**Issue by mkanet** [flixlix/power-flow-card-plus#444]
**Describe the bug**
If I add: `display_zero_tolerance` to Solar, the flow from Grid to Battery will mysteriously disappear.  It should still be displayed:
![1](https://github.com/flixlix/power-flow-card-plus/assets/811008/9159f4cf-7767-4040-903e-cf572e9be3a3) 

**To Reproduce:**   
```yaml
  - type: custom:power-flow-card-plus
    entities:
      grid:
        name: PG&E
        entity: sensor.powerwall_site_power
        secondary_info:
          entity: sensor.pge_electric_cost_to_date
          unit_of_measurement: $
          unit_white_space: false
          color_value: true
        display_state: one_way
        color_circle: true
        color_icon: true
        color_value: true
        power_outage:
          entity: binary_sensor.powerwall_grid_status
          state_alert: 'off'
      solar:
        entity: sensor.powerwall_solar_power
        display_zero_tolerance: 20        #<----this is the line that causes the bug!!
        icon: mdi:solar-panel-large
        secondary_info:
          entity: sensor.openweathermap_forecast_cloud_coverage
          unit_of_measurement: '%'
          unit_white_space: false
          color_value: true
        color_icon: true
        color_value: true
      battery:
        entity: sensor.powerwall_battery_power
        state_of_charge: sensor.powerwall_charge_actual
        state_of_charge_unit: '%'
        state_of_charge_unit_white_space: false
        display_state: one_way
        color_state_of_charge_value: true
        color_icon: true
        color_circle: true
      home:
        entity: sensor.powerwall_load_power
        color_icon: true
        color_value: true
    watt_threshold: 999
    calculate_flow_rate: true
    w_decimals: 1
    kw_decimals: 1
    min_flow_rate: 2.2
    max_flow_rate: 6
    display_zero_lines:
      mode: hide
    clickable_entities: true
    use_new_flow_rate_model: true
    max_expected_power: 5000`
```

**Expected behavior**  I had to remove `display_zero_tolerance: 20` from solar in order for it to work correctly:
![2](https://github.com/flixlix/power-flow-card-plus/assets/811008/f4eeecff-9778-4024-9bdb-00768653c058)

**Additional context**
This happens when there is supposed to be a flow from Grid to Battery.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by R-Fiandra** [comment]
Hi @mkanet ,
for the same issue i applied this workaround:

Create a new entity from template on configuration.yaml like this:
`template:
  sensors:

    new_production_FV:
        friendly_name: "Produzione fotovoltaico new"
        unit_of_measurement: 'W'
        value_template: >-
            {% set power_FV = states('sensor.shellyem_1234567_channel_1_power')|float %}
            {% if power_FV >= 8 %}
                {{- power_FV }}
            {% else %}
                0
            {% endif %}`
(In this case the number 8 used in the first "if" is my tollerance to consider the FV system off)

Then use this new sensor created into the value of the solar entity and remove the display_zero_tolerance
I read that the same issue exist on the power-flow-card integration (no plus)
I know that the bug remains but at the moment you can solve in this way

**Comment by mkanet** [comment]
> Hi @mkanet , for the same issue i applied this workaround:
> 
> Create a new entity from template on configuration.yaml like this:
> 
> ```
> template:
>   sensors:
> 
>     new_production_fv:
>         friendly_name: "Prod FV New"
>         unit_of_measurement: 'W'
>         value_template: >-
>             {% set power_FV = states('sensor.shellyem_1234567_channel_2_power')|float %}
>             {% if power_FV >= 8 %}
>                 {{- power_FV }}
>             {% else %}
>                 0
>             {% endif %}
> ```
> 
> (In this case the number 8 used in the first "if" is my tollerance to consider the FV system off)
> 
> Then use this new sensor created into the value of the solar entity and remove the display_zero_tolerance I read that the same issue exist on the power-flow-card integration (no plus) I know that the bug remains but at the moment you can solve in this way

Thank you so much.  I know you're going to think I'm completely dumb.. but, I don't even know what "FV" stands for.  I also don't know what source sensor name to use in my template code below instead of `sensor.shellyem_1234567_channel_2_power` .  I am using all original sensor names provided by the Tesla Powerwall Integration.  

Is it `sensor.powerwall_site_now` by chance (entity that displays real-time `Grid` power)?

Is so, does the below code look right?  
```yaml
template:
  sensors:

    powerwall_site_now_mod:
        friendly_name: "Powerwall Site Now Mod"
        unit_of_measurement: 'W'
        value_template: >-
            {% set grid_power = states('sensor.powerwall_site_now')|float %}
            {% if grid_power >= 8 %}
                {{- grid_power }}
            {% else %}
                0
            {% endif %}
```

New card code:

```yaml
  - type: custom:power-flow-card-plus
    entities:
      grid:
        name: PG&E
        entity: sensor.powerwall_site_now_mod
```

**Comment by ziptbm** [comment]
@mkanet This is just a guess and i could be way off....but my first thought was that it was probably similar to PV.  It looks like Photovoltaic in Italian is "fotovoltaico."  Literally a wild guess based on @R-Fiandra 's username...I could be wrong here...

If my assumption is correct, you probably want to try this workaround with the `sensor.powerwall_solar_now` sensor since it's trying to correct the solar value. 

```
            {% set power_PV = states('sensor.powerwall_solar_now')|float %}
            {% if power_PV >= 8 %}
                {{- power_PV }}
            {% else %}
                0
            {% endif %}
```

I'm going to try this myself and see if it helps since I've experienced the exact same bug when my system charges the battery from the grid.  

Side question - weren't you using APF template sensors instead of the native ones?  If so, would you want to use the native powerwall solar sensor or the APF Generation Entity?

**Comment by mkanet** [comment]
@ziptbm thank you for reply back.  But, I'll try using it with .008kW instead of 8.

**Comment by ziptbm** [comment]
It looks like this worked.   I ended up modifying the APF Generation Entity for mine and here's what I'm seeing now.

<img width="438" alt="Screenshot 2024-01-16 at 10 21 51" src="https://github.com/flixlix/power-flow-card-plus/assets/46136563/030caf81-abbd-43dd-8bfc-d0efc1c6dc3b">

While the battery is technically charging form the gird, I really wish it showed up as being charged from my Home instead of the grid since it's consumption on my home panel, which has limits.  So, in this case it looks like my home isn't consuming that much.  I see this as if the grid were directly connected to my EVs, which wouldn't be right as that power that should go through my Home first.

**Comment by mkanet** [comment]
@ziptbm.  Normally, we should just be able to use the below `display_zero_tolerance: 8` card setting; however, I'm running into the bug described in my first post.  I think this issue is caused by the Tesla Powerwall realtime "Solar" and "Site" sensors since they display some data that **should be hidden (but not removed completely!)**.

```yaml
  - type: custom:power-flow-card-plus
    entities:
      grid:
        name: PG&E
        entity: sensor.powerwall_site_now
        display_zero_tolerance: 8
```
Instead of:
```yaml
      - name: "Powerwall Site Now Mod"
        state: >-
            {% set grid_power = states('sensor.powerwall_site_now')|float %}
            {% if grid_power >= 0.008 %}
                {{ grid_power }}
            {% else %}
                0
            {% endif %}
        unit_of_measurement: "kW"
```
Interestingly, I can't just omit permanently the data we're hiding above for any of my related template sensors (screenshot below), or they end up being way off (yes even the weird negative "impossible" solar power values).  The only exception was the battery charge sensor; which I had to make a small adjustment (below) so the value would be more like the Tesla app.  Everything else is VERY close to the Tesla app; also considering the Powerwall API updates its sensors more quickly (at different times) than the Tesla app updates its values.

```yaml
      - name: Powerwall Charge Actual
        unique_id: powerwall_charge_actual
        state_class: measurement
        unit_of_measurement: '%'
        device_class: battery
        state: "{{ '%.0f' | format(((states('sensor.powerwall_charge') | float(0) / 100.0) - 0.05) / 0.95 * 100) }}"
      - name: Powerwall Backup Reserve Actual
        unique_id: powerwall_backup_reserve_actual
        state_class: measurement
        unit_of_measurement: '%'
        state: "{{ '%.0f' | format(((states('sensor.powerwall_backup_reserve') | float(0) / 100.0) - 0.05) / 0.95 * 100) }}"
```
![Solar](https://github.com/flixlix/power-flow-card-plus/assets/811008/83a3262f-595b-4f96-980c-beb4d3c55bc2)

**Comment by R-Fiandra** [comment]
Hi @mkanet,
sorry for the late response, i didn't understand if you really solved the issue.
the issue is caused by variable `display_zero_tolerance: 8` that if used (different from 0) and the Photovoltaic is showing a number greater than 0 also during night (normal behaviour, it happens also to me) then the integration will not show the line from grid to battery.
The workaround proposed by me is to remove the option `display_zero_tolerance: 8` from the card configuration in order to show lines from grid to battery but also the line from PV to battery also when is not in producion phase and modify the input sensor of the PV in order to show only values when greater than the "non production phase/night time".

In my case, using the template below (that need to be copied or integrated inside the configuration.yaml) i'll hide and interpret all value less than 8 (that is my threshold for consider the PV on non production state) as 0.
So, if the original sensor, in my case `sensor.shellyem_1234567_channel_2_power` (used to measure the PV power) is displaying a value like 5 the new sensor created `new_production_pv` will show 0, so only when the original sensor communicate a value greater than 8 the new sensor will show the same original value.

Using the new sensor `new_production_pv` inside the power flow card plus instead of the original in this way you enabled the zero tolerance implicitly, using the template function and avoiding this bug

```
template:
  sensors:

    new_production_pv:
        friendly_name: "Prod PV New"
        unit_of_measurement: 'W'
        value_template: >-
            {% set power_PV = states('sensor.shellyem_1234567_channel_2_power')|float %}
            {% if power_PV >= 8 %}
                {{- power_PV }}
            {% else %}
                0
            {% endif %}
```

I hope this helps you

OOT: can you please share how did you add the sensor estimated outage battery runtime under the card, with the bar of percentage and status?

Regards,

**Comment by mkanet** [comment]
> I hope this helps you
> 
> OOT: can you please share how did you add the sensor estimated outage battery runtime under the card, with the bar of percentage and status?
> 
> Regards,

Sorry, if I wasn't clear.  **Yes, it is a very good work-around.** Thank you.  I was just hoping this issue would catch the attention of the author of `power-flow-card-plus` to fix the bug for real in the card code; which might not be feasible due to the complexity of this issue.

OOT:  I recently added the code for the estimated outage battery runtime.  The code is below.  It won't be perfect; just like the one builtin to the Tesla App; but it should be a good guideline.   **The estimate I used is based on your average battery usage in the last 24 hours.**  If your battery usage in the last 24 hours is typical usage, it should be relatively accurate.  Note;  the **last 24 hours average** is configurable in the statistics sensor below for fine-tuning.  it is possible that it would be more accurate when using **last 12 hours of average battery usage** instead. I haven't tried that yet.

Replace `sensor.powerwall_load_now` with your real-time House load sensor below:

```yaml
#configuration.yaml
template:
  - sensor:
      - name: Powerwall Charge Actual
        unique_id: powerwall_charge_actual
        state_class: measurement
        unit_of_measurement: '%'
        device_class: battery
        state: "{{ '%.0f' | format(((states('sensor.powerwall_charge') | float(0) / 100.0) - 0.05) / 0.95 * 100) }}"
      - name: Powerwall Backup Reserve Actual
        unique_id: powerwall_backup_reserve_actual
        state_class: measurement
        unit_of_measurement: '%'
      - name: "Estimated Battery Life Hours Remaining"
        unit_of_measurement: "hours"
        state: >
          {% set battery_percentage = states('sensor.powerwall_charge_actual') | float(default=0) %}
          {% set total_battery_capacity_kWh = 27 %}
          {% set average_load_kW = states('sensor.recent_powerwall_house_load_average') | float(default=0) %}
          {% set available_battery_kWh = (total_battery_capacity_kWh * battery_percentage) / 100 %}
          {% if average_load_kW > 0 %}
            {% set estimated_hours_remaining = available_battery_kWh / average_load_kW %}
            {{ '%.1f' | format(estimated_hours_remaining) if estimated_hours_remaining > 0 else None }}
          {% else %}
            None
          {% endif %}
      - name: "Outage Battery Runtime Estimate"
        state: >
          {% set battery_percentage = states('sensor.powerwall_charge_actual') | float(default=0) %}
          {% set total_capacity_kWh = 27 %}
          {% set average_load_kW = states('sensor.recent_powerwall_house_load_average') | float(default=0) %}
          {% set available_kWh = (total_capacity_kWh * battery_percentage) / 100 %}
          {% if average_load_kW > 0 %}
            {% set hours_remaining = available_kWh / average_load_kW %}
            {% set depletion_time = now() + timedelta(hours=hours_remaining) %}
            {{ depletion_time.strftime('%-I:%M %p') if hours_remaining > 0 else None }}
          {% else %}
            None
          {% endif %}

sensor:
  - platform: statistics
    name: "Recent Powerwall House Load Average"
    entity_id: sensor.powerwall_load_now
    state_characteristic: mean
    max_age:
      hours: 24
```
**NOTE:** try changing `hours: 24` above in the statistics sensor to `hours: 12` to see if it is more accurate than 24 hours average for your case.  It is hard to say how many hours average the Tesla app uses to calculate this; however, it should be the same kind of calculation; regardless.


```yaml
#Lovelace card code (you can use your own card here if you wish):
  - type: custom:button-card
    entity: sensor.estimated_battery_life_hours_remaining
    tap_action:
      action: more-info
    layout: icon-label
    size: 20%
    color_type: card
    show_name: true
    show_state: true
    show_icon: false
    show_units: true
    card_mod:
      style: |
        ha-card {
          height: auto;
          padding-bottom: 25px !important;
          padding-left: 7px !important;
          background: transparent !important;
          box-shadow: none;
          border-top: none;
          margin: 0;
        }
    styles:
      grid:
        - grid-template-areas: '"n s"'
        - grid-template-columns: max-content min-content
        - grid-template-rows: 1fr
      name:
        - font-size: 14px
        - font-weight: 400
        - justify-self: start
        - padding-left: 22px
        - margin-right: 10px
        - white-space: nowrap
        - color: '#838383'
      state:
        - font-size: 14px
        - font-weight: 400
        - justify-self: start
        - padding-left: 0
        - color: '#B7A064'
        - margin-top: 1.8px
    name: 'Estimated outage battery runtime:'
    state_display: >
      [[[ return states['sensor.outage_battery_runtime_estimate'].state +
      '&nbsp; (' + states['sensor.estimated_battery_life_hours_remaining'].state
      + ' hours)' ]]]
```

**Comment by R-Fiandra** [comment]
Hi @mkanet,
thank you for the explanation, i already have the entities that calculate the estimate time, status and percentage.
My question was how did you insert these three entities under the power flow card with this graphics like unique panel in the dashboard. (Probably is more simple than i think but i don't know how in this moment)

**Comment by mkanet** [comment]
> Hi @mkanet, thank you for the explanation, i already have the entities that calculate the estimate time, status and percentage. My question was how did you insert these three entities under the power flow card with this graphics like unique panel in the dashboard. (Probably is more simple than i think but i don't know how in this moment)

I modified [button card](https://github.com/custom-cards/button-card) (code below) to display the sensor data the way I wanted it to show.  I'm sure there are simpler ways to display this data; but, this was the only way I could get it to look exactly the way I wanted it to look.  Then, I used card-mod again to seamlessly append the button-card below to the other cards above it (in a vertical [stack-in-card](https://github.com/custom-cards/stack-in-card) configuration).  If you want me to share the code for the entire vertical stack-in-card, just let me know.  It is huge; but, I can post it on pastebin or something like that.

```yaml
  - type: custom:button-card
    entity: sensor.estimated_battery_life_hours_remaining
    tap_action:
      action: more-info
    layout: icon-label
    size: 20%
    color_type: card
    show_name: true
    show_state: true
    show_icon: false
    show_units: true
    card_mod:
      style: |
        ha-card {
          height: auto;
          padding-bottom: 25px !important;
          padding-left: 7px !important;
          background: transparent !important;
          box-shadow: none;
          border-top: none;
          margin: 0;
        }
    styles:
      grid:
        - grid-template-areas: '"n s"'
        - grid-template-columns: max-content min-content
        - grid-template-rows: 1fr
      name:
        - font-size: 14px
        - font-weight: 400
        - justify-self: start
        - padding-left: 22px
        - margin-right: 10px
        - white-space: nowrap
        - color: '#838383'
      state:
        - font-size: 14px
        - font-weight: 400
        - justify-self: start
        - padding-left: 0
        - color: '#B7A064'
        - margin-top: 1.8px
    name: 'Estimated outage battery runtime:'
    state_display: >
      [[[ return states['sensor.outage_battery_runtime_estimate'].state +
      '&nbsp; (' + states['sensor.estimated_battery_life_hours_remaining'].state
      + ' hours)' ]]]
```

**Comment by R-Fiandra** [comment]
> I modified [button card](https://github.com/custom-cards/button-card) (code below) to display the sensor data the way I wanted it to show. I'm sure there are simpler ways to display this data; but, this was the only way I could get it to look exactly the way I wanted it to look. Then, I used card-mod again to seamlessly append the button-card below to the other cards above it (in a vertical [stack-in-card](https://github.com/custom-cards/stack-in-card) configuration). If you want me to share the code for the entire vertical stack-in-card, just let me know. It is huge; but, I can post it on pastebin or something like that.
> 

Yes please, i think i found the bar card and card-mod to recreate the bar for battery but not the css code to format, due to running out of context from thread bug, you can send me in private please?

**Comment by mkanet** [comment]
The full code in its entirety is below.  It is the same configuration I'm using currently for Tesla Powerwall.  It even includes the CSS code for the animations shown below (when power grid is not available) and also when battery is charging.  Customize it anyway you like.

**Charging Animation:**
![281861374-719b559a-3135-48df-9b42-d37f1b282b71](https://github.com/flixlix/power-flow-card-plus/assets/811008/63590e48-ff83-4121-a29b-d0ba24bb8a4d)

**Power Outage Animation:** 
![281863831-ac541612-93d4-408f-9bc1-17e4aa13471f](https://github.com/flixlix/power-flow-card-plus/assets/811008/d73b4229-5e47-4b35-be63-944779396bc2)

The CSS will modify **Power-Flow-Card-Plus** when you use `power_outage` like below:

```yaml
  - type: custom:power-flow-card-plus
    entities:
      grid:
        name: PG&E
        entity: sensor.powerwall_site_now_mod
        power_outage:
          entity: binary_sensor.grid_status
          state_alert: 'off'
```

**Full YAML card code:**
https://pastebin.com/vnvbx6w9
