### ISSUE TITLE
[SUPPORT] 

### ISSUE THREAD

**Issue by RALFISBORN** [flixlix/power-flow-card-plus#445]
Hello,

How is it possible to customize the text of "Zuhause"?

Thanks

```
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.Elektro_Bezug
      production: sensor.Elektro_Einspeisung
      display_state: one_way
      color_circle: true
  solar:
    entity: sensor.Elektro_Solar
    name: DachPV
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 3
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
title: Aktueller elektrischer Verbrauch
```

![image](https://github.com/flixlix/power-flow-card-plus/assets/47441243/5985e495-a6b0-4348-ad18-f97efd19ba18)
