### ISSUE TITLE
[BUG] Lines in the wrong place

### ISSUE THREAD

**Issue by ssorgatem** [flixlix/power-flow-card-plus#462]
**Describe the bug**
The lines don't connect

**To Reproduce**
This is my config:

```
type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.power_meter_m
    display_state: two_way
    color_icon: true
    invert_state: true
    color_circle: true
  solar:
    entity: sensor.inverter_active_power_m
    display_zero_state: false
    invert_state: false
    use_metadata: false
    color_value: false
  individual:
    - entity: sensor.endoll_prova_1_potencia
      name: Prova
      icon: mdi:heat-pump
      color: '#ff0000'
      display_zero: true
    - entity: sensor.caldera_active_power
      name: Caldera
      icon: mdi:water-boiler
      color: '#9541f0'
      display_zero: true
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    color_icon: true
    display_zero: true
    state_type: power
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
min_flow_rate: 0.75
max_flow_rate: 7
max_expected_power: 4500
min_expected_power: 0.01
watt_threshold: 10000
transparency_zero_lines: 0
kw_decimals: 3
```

**Expected behavior**
Well, it's obvious
**Screenshots**
This is how it looks now:

![image](https://github.com/flixlix/power-flow-card-plus/assets/108138/d7c7707e-785b-461a-8428-e51d1663ea95)

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Chrome
 - Version latest

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x ] I have the latest version of the card installed.

- [ x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.
