### ISSUE TITLE
[BUG] wrong colors in secondary entities, wrong connection lines on some resolutions

### ISSUE THREAD

**Issue by tigers75** [flixlix/power-flow-card-plus#483]
**Describe the bug**
The color of the first entity is not applied; it is instead applied to the second entity, but only to the bubble.

**To Reproduce**
add 2 secondary entities, customize the colors in both, set icon, bubble and text color to be the same.

**Expected behavior**
Each bubble, icon and value should get the color

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/37505492/980ad9f6-b76c-49fe-9314-ce7ee9e7a1eb)

**Browser Console Errors**
None

**Desktop (please complete the following information):**
 - OS: Windows 10, iOS and Android apps
 - Browser: Any
 - Version -

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: iOS or Android
 - Browser: the official HA app
 - Version latest

**Additional context**

Code for the 2 entities as generated by the new card wizard:

```
    - entity: sensor.centrale_termica_power
      name: C. Termica
      icon: mdi:fireplace
      color_icon: true
      color_value: true
      color:
        - 173
        - 1
        - 1
      calculate_flow_rate: true
      show_direction: false
      inverted_animation: false
    - entity: sensor.highest_power_appliance
      color_icon: false
      color_value: false
      use_metadata: false
```

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by mbrockeu** [comment]
Also have the same issue with 0.2.0 Beta

**Comment by bkhrupa** [comment]
I have the same issue with 0.2.0-beta

I have 4 devices

```
individual:
  # 1
  - entity: sensor.sb_power
    name: Server Box
    color: '#984ea3'
  # 2
  - entity: sensor.pump_power
    name: Pump
    color: '#44739e'
  # 3
  - entity: sensor.house_boiler_power
    name: House Boiler
    color: '#00d2d5'
  #4
  - entity: sensor.fridge_power
    color: '#ff7f00'
    name: Fridge
```

The device `#1`, I manually switch to the solar station and often this device has zero consumption and disappear from card - this is ok

But after disappearing - colors for bubbles is shifted by one position. And has wrong colors:

* `#2` = #984ea3
* `#3` = #44739e
* `#4` = #00d2d5

Yes, I can put the Server Box (`#1`) entity to the end of list and this fixed colors swiching.
