### ISSUE TITLE
combined entities not handling negative flows

### ISSUE THREAD

**Issue by arrikhan** [flixlix/power-flow-card-plus#50]
Combined entities when a flow is positive/negative are not treated as inward/outward flows on flow-card respectively.

Negative flow on grid should show feed in from either battery or solar but it shows as an outward flow of negative number. the same occurs for battery. (see pic)

![image](https://user-images.githubusercontent.com/13254846/229706369-13108550-e26a-4a20-bafb-df1762ac0734.png)

Config being used for combined entities for power on Fronius Smartmeter and Telsla Powerwall.

```yaml
title: Power Flow
entities:
  grid:
    entity:
      consumption: sensor.solarnet_power_grid
  solar:
    entity: sensor.solarnet_power_photovoltaics
  battery:
    entity:
      consumption: sensor.powerwall_battery_now
    state_of_charge: sensor.powerwall_charge
```

**Comment by flixlix** [comment]
Your code should look like this in your case since you are using combined entities

```yaml
title: Power Flow
entities:
  grid:
    entity: sensor.solarnet_power_grid
  solar:
    entity: sensor.solarnet_power_photovoltaics
  battery:
    entity:
      consumption: sensor.powerwall_battery_now
    state_of_charge: sensor.powerwall_charge
```
