### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gcoan** [flixlix/power-flow-card-plus#512]
**Describe the bug**
I've been trying out the v0.2.0-beta release, and it works really well, but I've found a couple of bugs and a couple of examples where it doesn't quite do what I want.

I have two inverters each with their own solar array, and battery on each, so previously I had to have two PowerFlowCard+'s to monitor each setup individually:
![image](https://github.com/flixlix/power-flow-card-plus/assets/142018870/3ffd2830-97d3-43db-bfcb-7e34f7ae8a0d)

But as each card doesn't know about the other, you get strange results such as negative house consumption appearing in one card where the two sets of solar panels are sharing the house load.

My ideal would be to have a single PF+ card showing all panels, batteries and the house load, and with the beta version allowing 4 individual devices, this works surprisingly well:
![image](https://github.com/flixlix/power-flow-card-plus/assets/142018870/8053319b-6615-4fde-947c-44542f8a6735)

Limitations I have found with this:
1. Calculation of the house load is incorrect, as Solar 2 and Battery 2 can both be contributing power into the home, the home load calculation doesn't seem to take account of this
![image](https://github.com/flixlix/power-flow-card-plus/assets/142018870/8ba722d2-46ab-4b7e-9df2-19208a6a49af)

2. There's no direction of travel shown on the power flow into battery 2 (they were both charging in the above screenshot)

3. The power meter in the battery 2 icon is static not dynamic based on the battery SoC (I appreciate this is an enhancement request!)

4. The animation of 'flow rate' from solar 2 and battery 2 seem to be a lot slower than the flow rate from solar 1 and battery 1

Bug I found:
5. Power in kW is not being rounded correctly.
Here's the card earlier in the week on the 'non beta' release showing rounding working correctly:
![image](https://github.com/flixlix/power-flow-card-plus/assets/142018870/33e54ada-ca5f-4d82-ae4e-06048fe642da)

And here's the new beta card with kW rounding not being performed:
![image](https://github.com/flixlix/power-flow-card-plus/assets/142018870/ecf47404-03ef-4039-ba5e-cbf4b605f6dc)

Here's the card config I used:
```
  - type: custom:power-flow-card-plus
    title: G182 PowerFlow+
    use_new_flow_rate_model: true
    w_decimals: 0
    kw_decimals: 1
    min_flow_rate: 0.75
    max_flow_rate: 10
    max_expected_power: 2600
    min_expected_power: 0.01
    watt_threshold: 1000
    transparency_zero_lines: 0
    clickable_entities: true
    display_zero_lines:
      mode: show
      transparency: 50
      grey_color: null
    entities:
      battery:
        entity: sensor.g_yyyy_battery_power
        state_of_charge: sensor.g_yyyy_soc
        display_state: one_way
        name: GE1 Battery
      grid:
        entity: sensor.g_yyyy_grid_power
        invert_state: true
        use_metadata: false
      solar:
        entity: sensor.g_yyyy_pv_power
        display_zero_state: true
        name: GE1 Solar
      home:
        color_icon: true
        subtract_individual: false
      individual:
        - entity: sensor.h_xxxx_pv_power
          name: GE2 Solar
          icon: mdi:solar-power
          inverted_animation: true
          display_zero: true
          calculate_flow_rate: true
        - entity: sensor.h_xxxx_battery_power
          name: GE2 Battery
          icon: mdi:battery
          display_zero: true
          secondary_info:
            entity: sensor.h_xxxx_soc
            unit_of_measurement: '%'
          inverted_animation: false
          display_zero_state: false
          calculate_flow_rate: true
        - entity: sensor.extension_power
          name: Extension
          icon: mdi:home-outline
          color: red
          display_zero_tolerance: 50
          calculate_flow_rate: true
        - entity: sensor.ashp_power
          name: ASHP
          icon: mdi:heat-pump-outline
          color: '#9007DD'
          display_zero_tolerance: 50
```

I had to add inverted_animation and display_zero_state to the second solar and battery items to get them to display all the time and for the flow to go the right way round.

Appreciate this is a mixture of bug report and enhancement request, but I know support for multiple sources is a requested feature #23, this would get a fair way towards it with minimal effort. 
BTW I actually have a 3rd solar array (no batteries), so would be good to include that as well, but to be honest just getting the two main ones on one consistent card would be a big step forward.

**Smartphone (please complete the following information):**
iPadOS 17.3 Home Assistant Companion App

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.
