### ISSUE TITLE
individual not displayed

### ISSUE THREAD

**Issue by lowrisk75** [flixlix/power-flow-card-plus#526]
what ever I do, even  using the template, with valid sensor, the individual won't work (e.g ev car).
rest work 

```
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.electric_meter_channel_1_power
    color_icon: solar
  fossil_fuel_percentage:
    entity: sensor.grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Non Fossil
    state_type: power
  grid:
    icon: mdi:ab-testing
    name: Provider
    entity:
      production: sensor.returned_to_the_grid
      consumption: sensor.electric_meter_channel_1_power
  solar:
    icon: mdi:solar-panel-large
    entity: sensor.total_solar_production
  battery:
    name: Batery
    icon: mdi:home-battery-outline
    entity:
      consumption: sensor.solarinverters
      production: sensor.battery_solar_in_power
      state_of_charge: sensor.battery_battery_level
  individual:
    - entity: sensor.proxmox_power_2
      icon: mdi:car
      name: Denim Flash
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 10000
clickable_entities: true
title: Electricity

```
