### ISSUE TITLE
Individual entities is not showing

### ISSUE THREAD

**Issue by SAOPP** [flixlix/power-flow-card-plus#536]
Hey!

I tried to play with the card, but I don’t understand at all why individual entities are not drawn on the card in my configuration?

Here is my example:

```
    - type: custom:power-flow-card-plus
      entities:
        home:
          entity: sensor.electricity_input_wh_to_kwh_daily
          icon: mdi:home-lightning-bolt-outline
          color_icon: true
          secondary_info:
            entity: sensor.corridor_input_electricity_meter_current_l2
            unit_of_measurement: A
        grid:
          entity: sensor.corridor_input_electricity_meter_power_l2
          icon: mdi:transmission-tower-export
          display_state: one_way
          color_icon: true
          color_circle: true
        individual:
          - entity: sensor.kitchen_fridge_power_socket_power
            name: Fridge
            icon: mdi:fridge
            color: "#80b8ff"
            color_icon: true
      watt_threshold: 1800
      use_new_flow_rate_model: true
      clickable_entities: true
      w_decimals: 1
      kw_decimals: 1
```

![image](https://github.com/flixlix/power-flow-card-plus/assets/5647009/67ce6e9d-0a9f-4b93-b719-64affeeb0474)

Where is the Fridge Carl? :-D Or maybe I not understood manual correctly?
