### ISSUE TITLE
[BUG] v0.2.1: Individual doesn't show secondary info

### ISSUE THREAD

**Issue by ma9mwah** [flixlix/power-flow-card-plus#567]
**Describe the bug**
when adding a secondary info to a individual circle it doesn't appear.

![image](https://github.com/flixlix/power-flow-card-plus/assets/21035345/4d3d1e37-2d67-4e1e-94fd-24c1bcfa2c32)

This is the code the GUI created:
```  
individual:
    - entity: sensor.myenergi_eddi_xxxxxx_power_ct_internal_load
      name: Eddi
      color:
        - 255
        - 255
        - 0
      display_zero: true
      secondary_info:
        entity: sensor.myenergi_eddi_xxxxxx_energy_used_today
        unit_of_measurement: kWh
        decimals: 1
        unit_white_space: true
        display_zero: true
        color_value: false
        accept_negative: false
        icon: ''
      show_direction: false
      color_value: false
      color_icon: true
      display_zero_state: true
      calculate_flow_rate: false
      use_metadata: false
      icon: mdi:water
```
