### ISSUE TITLE
[BUG] "Home" value not show

### ISSUE THREAD

**Issue by Boia11** [flixlix/power-flow-card-plus#571]
**Describe the bug**
After some hours the entity set into "home" appear fixed to 0 W.
I try to enable "override state" option, it appaear correctly but without animation.

**Screenshots**
![Screenshot 2024-04-16 155510](https://github.com/flixlix/power-flow-card-plus/assets/10048197/bb1d6e49-0fe8-484f-b30a-f1f90226e4d3)
![Screenshot 2024-04-16 155541](https://github.com/flixlix/power-flow-card-plus/assets/10048197/5d9959b5-59f4-4e1f-b15a-b60ef243acc8)

**Home Assistant:**
 - Core: 2024.4.3
 - Supervisor: 2024.04.0
 - Operating System: 12.2
 - Frontend: 20240404.2

**HACS:**
 - HACS: 1.34.0
 - Frontend: 20220906112053

**Power Flow Card Plus:**
 - Version: [v0.2.1](https://github.com/flixlix/power-flow-card-plus/releases/tag/v0.2.1)
 - Configuration:
```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.zcsazzurro_battery_1_power
    state_of_charge: sensor.zcsazzurro_battery_1_soc
    invert_state: true
  grid:
    entity: sensor.zcsazzurro_activepower_pcc_total
    invert_state: true
  solar:
    entity: sensor.zcsazzurro_pv1_power
    display_zero_state: true
    secondary_info:
      entity: sensor.zcsazzurro_pv2_power
      display_zero: true
  home:
    entity: sensor.zcsazzurro_activepower_load_sys
    secondary_info:
      entity: sensor.zcsazzurro_radiator_temperature_1
      unit_of_measurement: °C
      decimals: 0
    use_metadata: false
    override_state: false
clickable_entities: true
display_zero_lines:
  mode: transparency
  transparency: 75
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
disable_dots: false
dashboard_link: /energy
```
