### ISSUE TITLE
In the Fossil Fuel section the "Color of Value" toggle switch of the main entity overrides the secondary.

### ISSUE THREAD

**Issue by Ndrinta** [flixlix/power-flow-card-plus#575]
**Describe the bug**
In the _Fossil Fuel_ section the "Color of Value" toggle switch of the main entity overrides the secondary.
Seems to be OK elsewhere but not fully tested.

**To Reproduce**
Set the "Color of Value" toggle to true for main entity and to false for secondary.

```
  fossil_fuel_percentage:
    color_icon: false
    entity: sensor.grid_non_fossil_fuel_percentage
    secondary_info:
      entity: sensor.grid_non_fossil_fuel_percentage
      unit_of_measurement: '%'
      display_zero: false
      unit_white_space: false
      color_value: false # <- Secondary Entity Color: FALSE
    display_zero: true
    color_value: true # <- Main Entity Color: TRUE
    unit_white_space: true
```

**Expected behavior**
Apply the color to only main entity and not (black) secondary.

**Screenshots**
![image](https://github.com/flixlix/power-flow-card-plus/assets/4704172/0e5e9c8b-a57f-4030-9e35-d5e01f4b61cb)

**Browser Console Errors**
N/A

**Desktop (please complete the following information):**
Core 2024.4.3
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2

**Smartphone (please complete the following information):**
N/A
