### ISSUE TITLE
[BUG] switch entity not shown as secondary info

### ISSUE THREAD

**Issue by PulsarFX** [flixlix/power-flow-card-plus#583]
Previous to 0.2 it was possible to add a switch sensor to the secondary info.
This is still possible to do, but the icon is not shown in the circle. 
Clicking this icon had opened the standard switch dialog for this entity.

old code:
```
  individual1:
    show_direction: true
    inverted_animation: false
    entity: sensor.steckdose_11_pc_power
    name: PC Büro
    icon: mdi:desktop-classic
    use_metadata: false
    secondary_info:
      entity: switch.steckdose_11_pc
      icon: mdi:electric-switch
    display_zero: true
    display_zero_state: false
clickable_entities: true
```
![grafik](https://github.com/flixlix/power-flow-card-plus/assets/4960210/50d8e76e-a795-4292-983d-8e0fb62df6f8)

new code:
```
  individual:
    - entity: sensor.steckdose_11_pc_power
      name: PC Büro
      icon: mdi:desktop-classic
      secondary_info:
        entity: switch.steckdose_11_pc
        icon: mdi:electric-switch
        display_zero: true
        unit_white_space: false
        accept_negative: true
        decimals: 0
      color_value: false
      color_icon: false
      show_direction: false
      use_metadata: false
      display_zero: true
      display_zero_state: true
      calculate_flow_rate: false
```
![grafik](https://github.com/flixlix/power-flow-card-plus/assets/4960210/6b3e6998-bc85-4844-87ab-3bd6dec431d7)
 

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

- [X] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

**Comment by flixlix** [comment]
hello @PulsarFX 
this is expected, because the card currently only supports numeric values for secondary info.

A workaround that would solve the issue is adding a template to your secondary sensor in addition to the sensor inside the `entity` property (this way you can still click inside the secondary info to see more info about your switch):

```yaml
- entity: sensor.car_charger
  secondary_info:
    entity: switch.car_charger
    template: '{{states(''switch.car_charger'')}}'
    color_value: true
    unit_of_measurement: '%'
    icon: mdi:battery-low
    display_zero: true
    unit_white_space: true
    accept_negative: true
```

**Comment by PulsarFX** [comment]
Nice workaround. :-D 
It's important to have the entity for secondary_info set to the same as the template. Otherwise the details won't open.
The modified code from my first post looks like this:

```
  individual:
    - entity: sensor.steckdose_11_pc_power
      name: PC Büro
      icon: mdi:desktop-classic
      secondary_info:
        entity: switch.steckdose_11_pc
        icon: mdi:electric-switch
        display_zero: true
        unit_white_space: false
        accept_negative: true
        decimals: 0
        template: '{{states(''switch.steckdose_11_pc'')}}'
```
