### ISSUE TITLE
[BUG] Individual devices doesn't appare in companion app

### ISSUE THREAD

**Issue by Gobolin80** [flixlix/power-flow-card-plus#586]
The individual devices are displayed correctly on Chrome, but they do not appear in the Companion App.
Before installing version 2.*, everything was working correctly.

**On Chrome in my PC/Mac:**

<img width="501" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/47695621/d413a8a3-6478-4644-8139-23d1f2679e04">

On Companion App:

<img width="857" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/47695621/263a8e9a-4eee-4893-8fdd-b57a887d9b9c">

This is my code (sorry for bad formatting):

```yaml
type: custom:power-flow-card-plus
entities:
  battery: {}
  grid:
    entity:
      consumption: sensor.potenza_acquistata_rete_realtime_watt
      production: sensor.potenza_ceduta_rete_realtime_watt
    color_icon: true
    color_circle: true
  solar:
    display_zero_state: true
    entity: sensor.potenza_prodotta_fotovoltaico_realtime_watt
    icon: mdi:solar-panel-large
    color_icon: true
    color_value: false
  home:
    entity: sensor.potenza_totale_assorbita_casa_realtime_watt
    color_icon: true
  fossil_fuel_percentage: {}
  individual:
    - entity: sensor.prism_power
      name: Tesla
      icon: mdi:car-electric
      secondary_info:
        entity: sensor.tesla_battery_level
        unit_of_measurement: '%'
      color:
        - 255
        - 128
        - 128
      color_icon: true
      color_value: false
      display_zero: false
    - name: Condizionatori
      entity: sensor.condizionatori_consumo_realtime_watt
      icon: mdi:air-conditioner
      color_icon: true
      color:
        - 120
        - 255
        - 167
      secondary_info:
        entity: sensor.condizionatori_accesi_count
        display_zero: false
        unit_of_measurement: split
      display_zero_tolerance: 20
    - entity: sensor.lavatrice_consumo_realtime_watt
      display_zero_state: false
      display_zero: false
      name: Lavatrice
      icon: mdi:washing-machine
      color:
        - 27
        - 193
        - 181
      color_icon: true
      display_zero_tolerance: 5
    - entity: sensor.asciugatrice_consumo_realtime_watt
      name: Asciugatrice
      icon: mdi:tumble-dryer
      display_zero: false
      color:
        - 218
        - 211
        - 16
      color_icon: true
      display_zero_tolerance: 5
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
title: Consumi istantanei
```
