### ISSUE TITLE
[BUG] v0.2.2: Individual 1 doesn't show unit of measurement when 0

### ISSUE THREAD

**Issue by cpohli** [flixlix/power-flow-card-plus#597]
**Describe the bug**
Now that (thanks to #567) the display zero is shown, it is missing the unit of measurement when the value actually IS zero.

**Expected behavior**
Even when the secondary sensor value is zero, the 0 AND unit of measurement should be shown.

**Screenshots**
<img width="105" alt="image" src="https://github.com/flixlix/power-flow-card-plus/assets/32699124/ed1a7e4c-dfd5-43e2-9c62-6412273b4035">

My code is looking like this:
```
          individual:
            - entity: sensor.smaev_3013072337_charging_station_power
              unit_white_space: true
              name: Wallbox
              display_zero: true
              secondary_info:
                display_zero: true
                unit_white_space: true
                unit_of_measurement: 'kWh'
                decimals: 1
                accept_negative: false
                entity: sensor.wallbox_daily_kwh
              icon: mdi:car-arrow-left
              color_icon: false
              color:
                - 221
                - 14
                - 24
```

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.
