### ISSUE TITLE
 Wrong unit displayed for battery charging

### ISSUE THREAD

**Issue by Diavolezza** [flixlix/power-flow-card-plus#61]
Battery loading is displayed in W, even if watt_threshold is set to 0. All other entries are fine and follow the directive
See attached picture.
<img width="410" alt="Bildschirmfoto 2023-04-12 um 12 35 44" src="https://user-images.githubusercontent.com/8983765/231435642-1467fa3e-25e5-477d-9592-bafe63cc4bf8.png">

**Comment by flixlix** [comment]
Hello,
can you please share your code? Otherwise I will not be able to help you

**Comment by Diavolezza** [comment]
```
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.home_usage
    color_icon: solar
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Nicht Fossil
    state_type: power
  grid:
    entity:
      consumption: sensor.pcomsume
      production: sensor.psupply
  solar:
    entity: sensor.summe_pv_produktion
  battery:
    entity:
      consumption: sensor.battery_production
      production: sensor.sma_storage_37_grid_power
    state_of_charge: sensor.sma_storage_37_battery_soc_total
watt_threshold: 800

```

**Comment by flixlix** [comment]
I Imagine the problem is that the battery consumption entity's state is negative so the threshold was not surpassed to display in kW.
The states should only be negative if you are using only one entity for the battery configuration, but in your case it should never be negative because you are using the [Split Entities Configuration](https://github.com/flixlix/power-flow-card-plus#split-entities).
It is not clear from the naming of your entity_id's but you should either have one entity providing positive and negative values, depending on the direction of the power or one entity for each direction. In that case, at least one entity must have a `0` state and neither should ever be negative.

**Comment by Diavolezza** [comment]
Oh, that could be possible. So this must something like that?
```
  battery:
    entity:
      consumption: 0
      production: sensor.battery_inveverted_2
    state_of_charge: sensor.sma_storage_37_battery_soc_total
```

battery_inverted_2 goes from -3700 to 3700.
Thank you!

**Comment by flixlix** [comment]
No, in case you have one entity that has negative states for one direction and positive states for the other direction, you can configure it like this:

```yaml
    battery:
      entity: sensor.battery_inverted_2
      state_of_charge: sensor.sma_storage_37_battery_soc_total
```

Does this work as expected?
