### ISSUE TITLE
[SUPPORT] Card broke after update

### ISSUE THREAD

**Issue by LukasNitsche** [flixlix/power-flow-card-plus#640]
I am now on the latest update of the card, where it broke. Could someone please indicate what changes I have to make so it works and looks again as before without me having to set it up again new? Especially the color of the individual device and the color of unused lines should be the same.

```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_charge_discharge_power
    state_of_charge: sensor.battery_state_of_capacity
    invert_state: true
    state_of_charge_unit_white_space: false
  grid:
    entity: sensor.power_meter_active_power
    invert_state: true
  solar:
    entity: sensor.inverter_input_power
    display_zero_state: true
    secondary_info:
      decimals: 1
  home:
    entity: sensor.leistungsabnahme_haus
  individual1:
    unit_of_measurement: W
    name: Tesla
    icon: mdi:car-electric
  individual2:
    entity: sensor.tesla_charging_power_home_accurate_solar
    name: Tesla
    icon: mdi:car-electric
    calculate_flow_rate: false
    secondary_info:
      entity: sensor.model_3_von_lukas_batteriestand
      icon: mdi:battery-10
      unit_of_measurement: '%'
clickable_entities: true
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
dashboard_link: /energy
title: Power distribution now
```

**Comment by drluc1** [comment]
You have to change the "individual" section. Only works in the browser tho, in the App its bugged and doesn't show the individual tabs.
It will look like this:
```
  individual:
    - entity: sensor.gesamtleistung_steckdosen
      name: Steckdosen
      icon: mdi:power-plug
    - entity: sensor.smart_switch_23111619203500510d0348e1e9e27427_power
      name: PC Luc
      icon: mdi:laptop
    - entity: sensor.smart_switch_23111606661952510d0348e1e9e281d6_power
      name: Fernseher
      icon: mdi:monitor
```
