### ISSUE TITLE
[FEATURE REQUEST] customizable tap / click action

### ISSUE THREAD

**Issue by brechtvhb** [flixlix/power-flow-card-plus#660]
I would like to be able to set the tap action for each circle.
For each circle i have a page that shows more detail than just the entity. I would be able to navigate to those pages  when tapping the circle.

Eg:

```
  solar:
    icon: fapro:solar-panel
    entity: sensor.solar_total_power_output
    tap_action:
      action: navigate
      navigation_path: /lovelace/solar
```
