### ISSUE TITLE
[BUG] Solar not feeding home directly

### ISSUE THREAD

**Issue by gitzone83** [flixlix/power-flow-card-plus#666]
**Describe the bug**
Solar not feeding home directly

**To Reproduce**

Full config code is below, just removed S/N for the Envoy

```
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.envoy_SERIAL_current_power_consumption
      production: sensor.envoy_SERIAL_current_power_production
    color_circle: true
    color_icon: true
    invert_state: true
    name: Grid
    icon: mdi:transmission-tower
    color_value: true
  solar:
    entity: sensor.envoy_SERIAL_current_power_production
    color_icon: true
    color_value: true
    name: Solar
    icon: mdi:solar-power-variant-outline
    display_zero_state: false
    invert_state: false
    use_metadata: true
  battery:
    entity: sensor.envoy_SERIAL_current_battery_discharge
    display_state: two_way
    color_circle: true
    color_icon: true
    color_state_of_charge_value: true
    state_of_charge_unit: W
    state_of_charge_decimals: 3
    show_state_of_charge: true
    state_of_charge_unit_white_space: true
    color_value: true
  home:
    color_icon: true
    color_value: true
    icon: mdi:home
    name: Home
    subtract_individual: true
    override_state: false
  fossil_fuel_percentage:
    state_type: power
    entity: sensor.electricity_maps_grid_fossil_fuel_percentage
    name: Fossil
    icon: mdi:barrel
    color_icon: true
    color_value: true
    unit_white_space: false
    display_zero: true
    display_zero_state: false
watt_threshold: 1000
display_zero_lines:
  mode: hide
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
kw_decimals: 3
w_decimals: 0
disable_dots: false
max_flow_rate: 5
min_flow_rate: 0.5
use_new_flow_rate_model: true
clickable_entities: true
max_expected_power: 12000
min_expected_power: 1000

```

![image](https://github.com/user-attachments/assets/0008134d-7502-4917-9409-7f4b81bd1d19)

**Expected behavior**
I'd expect solar power to first feed home and battery, and then only surplus going to grid export. 

**Screenshots**

**Browser Console Errors**
N/A

**Desktop (please complete the following information):**
Multiple, Windows and Linux machines, same issue persists

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [ ] I have cleared my browser cache **after** installing, updating and configuring the card.

- [ ] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.
