### ISSUE TITLE
[FEATURE REQUEST] 2024.9 Wide Sections for more than 4 individual devices

### ISSUE THREAD

**Issue by b1ggi** [flixlix/power-flow-card-plus#697]
**Is your feature request related to a problem? Please describe.**
"Only" 4 devices atm possible

**Describe the solution you'd like**
With the wide sections on 2024.9 on sections dashboard now available, it is  possible to resize and widen cards horizontally or vertically, making room for more individual devices

**Describe alternatives you've considered**
n/a

**Additional context**
Here is a exaggerated example of whats maximum possible (can be resized), the section "Garage" has 7 width and 8 height, 
![image](https://github.com/user-attachments/assets/2bb86fac-7917-4cf0-831d-dc5099f9ce11)

section 7 width
![image](https://github.com/user-attachments/assets/7763916e-bc9c-4216-a8c4-0e820f5f886e)

card 8 height
![image](https://github.com/user-attachments/assets/70e9edaf-1a16-4081-ab46-4e014f38a48d)

**Comment by IIIdefconIII** [comment]
i have some simulkair issue here https://github.com/flixlix/power-flow-card-plus/issues/696

**Comment by bogvalerio** [comment]
It will be great to have the possibility to shown 6 or better 8 devices . I have , and I think not only me , lot of meter in my home and with 4 devices I can monitor only 4 .

**Comment by Meigl89** [comment]
I can agree to this request. Even if it was among each other, that would be great. And when Ikea brings this new powerplug that includes a meter in october, I guess this would be good.

**Comment by IIIdefconIII** [comment]
https://github.com/flixlix/power-flow-card-plus/issues/696#issue-2526660029

**Comment by b1ggi** [comment]
https://github.com/flixlix/power-flow-card-plus/pull/700 first step which is necessary, i would give my feature request myself a try to program it.

**Comment by MS-HACS** [comment]
Same here. Would really love to add more individual entities, also another mini PV installation which is not covered by the main one and only lowers the consumption of our household. 
Also, cascading these entities would be great, e.g. for appartment houses.

**Comment by scorpio2001de** [comment]
+1

**Comment by bbr111** [comment]
+1

**Comment by b1ggi** [comment]
now that https://github.com/flixlix/power-flow-card-plus/issues/578 is implemented, it could be possible to realize this feature request.

**Comment by Roycinger** [comment]
+1

**Comment by lr-apro** [comment]
+1

**Comment by Sm0ukie** [comment]
+1

**Comment by Domme0506** [comment]
+1

**Comment by nezzergetti** [comment]
+1 YES PLZ

**Comment by FabianNiesen** [comment]
+1

**Comment by rob0101** [comment]
+1
I've exceeded the limit.

**Comment by IIIdefconIII** [comment]
> +1 I've exceeded the limit.

owwwwwwwwww shittttt... that would be awesome going to check out later today to merge this config

<img width="1140" height="2924" alt="Image" src="https://github.com/user-attachments/assets/059631ce-57ed-4485-b97b-24417499c03c" />

```
type: grid
cards:
  - type: heading
    icon: mdi:fridge
    heading: Devices Meters
    heading_style: title
    card_mod:
      style: |
        ha-card {
          background: green !important;
          text-align: center;
        }
  - type: vertical-stack
    cards:
      - type: custom:power-flow-card-plus
        entities:
          grid:
            secondary_info: {}
            entity:
              consumption: sensor.electricity_meter_feed_in_tariff_1
        clickable_entities: true
        display_zero_lines:
          mode: show
          transparency: 50
          grey_color:
            - 189
            - 189
            - 189
        use_new_flow_rate_model: true
        min_flow_rate: 0.75
        max_flow_rate: 6
        max_expected_power: 2000
        min_expected_power: 0.01
        watt_threshold: 1000
        transparency_zero_lines: 0
        sort_individual_devices: false
        kw_decimals: 0
        w_decimals: 0
        card_mod:
          style: |
            ha-card {
            background: none !important;  
            border: none !important;
            }
      - type: custom:power-flow-card-plus
        entities:
          battery:
            state_of_charge: sensor.matter_server_cpu_percentage
          grid:
            secondary_info: {}
            entity:
              "0": s
              "1": e
              "2": "n"
              "3": s
              "4": o
              "5": r
              "6": .
              "7": e
              "8": l
              "9": e
              "10": c
              "11": t
              "12": r
              "13": i
              "14": c
              "15": i
              "16": t
              "17": "y"
              "18": _
              "19": m
              "20": e
              "21": t
              "22": e
              "23": r
              "24": _
              "25": f
              "26": e
              "27": e
              "28": d
              "29": _
              "30": i
              "31": "n"
              "32": _
              "33": t
              "34": a
              "35": r
              "36": i
              "37": f
              "38": f
              "39": _
              "40": "1"
              consumption: sensor.electricity_meter_feed_in_tariff_1
          individual:
            - entity: sensor.light_corner_left_power
              name: Corner Left
              secondary_info: {}
            - entity: sensor.light_ceiling_energy_2
              name: Ceiling
              secondary_info: {}
            - entity: sensor.light_corner_right_power
              name: Corner Left
              secondary_info: {}
          fossil_fuel_percentage:
            secondary_info: {}
        clickable_entities: true
        display_zero_lines:
          mode: show
          transparency: 50
          grey_color:
            - 189
            - 189
            - 189
        use_new_flow_rate_model: true
        kw_decimals: 0
        min_flow_rate: 0.75
        max_flow_rate: 6
        max_expected_power: 2000
        min_expected_power: 0.01
        watt_threshold: 1000
        transparency_zero_lines: 0
        sort_individual_devices: false
        title: Lights
        w_decimals: 0
        card_mod:
          style: |
            ha-card {
            background: none !important;  
            border: none !important;
            }
      - type: custom:power-flow-card-plus
        entities:
          battery:
            state_of_charge: sensor.matter_server_cpu_percentage
          individual:
            - entity: sensor.power_mysetup_energy
              secondary_info: {}
              name: My Setup
            - entity: sensor.power_plug_security_screen
              secondary_info: {}
              name: Sec. Screen
            - entity: sensor.power_plug_screen_left
              secondary_info: {}
              name: Left
              display_zero_state: false
              color_value: false
            - entity: sensor.power_plug_sreen_center
              secondary_info: {}
              name: Center
            - entity: sensor.power_mysetup_energy
          grid:
            secondary_info: {}
            entity:
              consumption: sensor.electricity_meter_feed_in_tariff_1
          fossil_fuel_percentage:
            secondary_info: {}
        clickable_entities: true
        display_zero_lines:
          mode: show
          transparency: 50
          grey_color:
            - 189
            - 189
            - 189
        use_new_flow_rate_model: true
        w_decimals: 0
        kw_decimals: 0
        min_flow_rate: 0.75
        max_flow_rate: 6
        max_expected_power: 2000
        min_expected_power: 0.01
        watt_threshold: 1000
        transparency_zero_lines: 0
        sort_individual_devices: false
        title: My Setup
        card_mod:
          style: |
            ha-card {
            background: none !important;  
            border: none !important;
            }
      - type: custom:power-flow-card-plus
        entities:
          battery:
            state_of_charge: sensor.matter_server_cpu_percentage
          individual:
            - entity: sensor.iiidefconiii_power_cinema_power
              name: Cinema
              secondary_info: {}
            - entity: sensor.power_plug_coffee
              secondary_info: {}
              icon: mdi:coffee
              name: Coffee
            - entity: sensor.smart_plug_power_2
              name: Air Purifier
              secondary_info: {}
          grid:
            secondary_info: {}
            entity:
              consumption: sensor.electricity_meter_feed_in_tariff_1
        clickable_entities: true
        display_zero_lines:
          mode: show
          transparency: 50
          grey_color:
            - 189
            - 189
            - 189
        use_new_flow_rate_model: true
        w_decimals: 0
        min_flow_rate: 0.75
        max_flow_rate: 6
        max_expected_power: 2000
        min_expected_power: 0.01
        watt_threshold: 1000
        transparency_zero_lines: 0
        sort_individual_devices: false
        title: Activity
        disable_dots: false
        kw_decimals: 0
        card_mod:
          style: |
            ha-card {
            background: none !important;  
            border: none !important;
            }

```
