### ISSUE TITLE
[BUG] Flow annimation from Grid to Battery & Home is mixed up

### ISSUE THREAD

**Issue by blacknell** [flixlix/power-flow-card-plus#769]
**Describe the bug**
There is no flow animation between Grid and Battery but there is to home (wrong)

**To Reproduce**
1. I created the config below

**Expected behavior**
There should be a rapid animation from Grid to Battery (5.3kW) but there is none. Likewise the flow animation from Grid to Home should be slow (326W).
**Screenshots**

https://github.com/user-attachments/assets/3b50318b-49d6-4d6c-927b-18b2523f026c

**Browser Console Errors**
If applicable, add Errors from the browser console.

**Desktop (please complete the following information):**
 - OS: MacOS 14.5
 - Chrome
 - 133.0.6943.127 

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

- [x] The issue is not related to the UI-Editor not being rendered: "s.entries is not a function". This is a known bug, and is caused by Card Mod. Check the warning this [readme section](https://github.com/flixlix/power-flow-card-plus#usage) for more information on how to fix it.

```
type: custom:power-flow-card-plus
entities:
  battery:
    state_of_charge: sensor.powerwall_percentage_charged
    entity:
      consumption: sensor.powerwall_battery_discharging_power
      production: sensor.powerwall_battery_charging_power
    invert_state: false
    color_circle: true
    state_of_charge_unit_white_space: false
    color:
      consumption:
        - 0
        - 176
        - 80
      production:
        - 255
        - 1
        - 0
    color_value: true
  grid:
    entity: sensor.octopus_energy_electricity_current_demand
    display_state: one_way
    secondary_info:
      template: >
        {{
        (states('sensor.octopus_energy_electricity_current_rate')|float*100)|round(3)
        }}p
  home:
    secondary_info: {}
    entity: sensor.powerwall_load_power
    subtract_individual: false
    override_state: true
  individual:
    - entity: sensor.ev_charger_power_active_import
      display_zero: true
      name: EV
      icon: mdi:ev-plug-type2
      secondary_info:
        template: |
          {{ states('sensor.audi_q4_e_tron_primary_engine_percent') }}%
        unit_white_space: true
        color_value: false
        unit_of_measurement: "%"
      display_zero_state: true
    - entity: sensor.untracked_power
      secondary_info: {}
      name: Untracked
      icon: mdi:lightbulb-question
      display_zero: true
    - entity: sensor.appliances_power
      secondary_info: {}
      name: Appliances
      display_zero: false
      icon: mdi:microwave
  fossil_fuel_percentage:
    secondary_info: {}
    entity: sensor.electricity_maps_grid_fossil_fuel_percentage
    state_type: percentage
    color_value: false
    name: Non Fossil
    display_zero: true
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_flow_rate: 6
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
```
