### ISSUE TITLE
[BUG] with v0.2.5

### ISSUE THREAD

**Issue by Dieter3Thomas** [flixlix/power-flow-card-plus#782]
- No "Bubbles" from Solar Power to Battery 

At the moment I get 92W Solar , and on Grid 268W .

Card Show 92W from Solart  to Battery ( No Flow Bubbels) and Home consume looks  like (Power Grid- SOLAR ) 
V 0.2.4 works like expect  

<img width="380" alt="Image" src="https://github.com/user-attachments/assets/fb628f8a-c3e2-4351-9c25-4f8a806e8c62" />

<img width="299" alt="Image" src="https://github.com/user-attachments/assets/ebfa504a-01fe-4470-9660-fc880e55b52f" />

**Comment by MarkWeber123** [comment]
The same here. Instead of Bubble Solar -> Battery I have a Grid -> Battery Bubble. 0.2.4 was fine

**Comment by jpawlowski** [comment]
Same here.

It might be related to PR https://github.com/flixlix/power-flow-card-plus/pull/742.

<img width="483" alt="image" src="https://github.com/user-attachments/assets/9083ed34-6256-4962-8a81-8ca660b04a52" />

As you can see, we've got 11 Watts here coming in from solar, but it is treated as coming from the grid instead. The Home wattage is something I calculate manually due to some speciality at my house (two measuring points and an EV right in between). Also, a lot of the consumers behind the Home icon are estimated by Powercalc, which is why there are some minor differences if you do the math manually from the screenshot.

This is my full definition which had worked fine before:

```yaml
type: custom:power-flow-card-plus
entities:
  battery:
    state_of_charge: sensor.solarflow_electric_level
    invert_state: true
    color_value: true
    color_icon: true
    color_circle: true
    show_state_of_charge: false
    color:
      consumption:
        - 255
        - 152
        - 0
      production:
        - 17
        - 157
        - 88
    entity:
      production: sensor.solarflow_output_pack_power
      consumption: sensor.solarflow_pack_input_power
    state_of_charge_unit_white_space: true
  grid:
    secondary_info: {}
    invert_state: false
    use_metadata: false
    color_value: true
    power_outage:
      entity: sensor.energiemonitor_netz_status
      icon_alert: mdi:meter-electric
    color_icon: true
    color_circle: true
    color:
      consumption:
        - 73
        - 143
        - 194
      production:
        - 0
        - 168
        - 168
    entity:
      consumption: sensor.tibber_leistung
      production: sensor.tibber_stromerzeugung
  solar:
    display_zero_state: false
    secondary_info:
      entity: sensor.solarflow_solar_input_power_energy_daily
      icon: ""
      unit_of_measurement: kWh
      decimals: 2
      display_zero: false
    color_value: false
    color_icon: true
    entity: sensor.solarflow_solar_input_power
  home:
    secondary_info:
      unit_white_space: true
    subtract_individual: false
    circle_animation: true
    override_state: true
    color_icon: true
    icon: ""
    use_metadata: true
    entity: sensor.energiemonitor_netto_gesamtwirkleistung
  fossil_fuel_percentage:
    state_type: percentage
    secondary_info: {}
    entity: sensor.electricity_maps_anteil_fossiler_energietrager
    display_zero: true
    display_zero_state: true
    color_value: false
    name: CO₂-arm
    color_icon: true
  individual:
    - entity: sensor.verbrauchsgruppe_licht_leistung
      secondary_info: {}
      icon: mdi:lightbulb-group
      color_value: false
      inverted_animation: false
      name: Licht
      color_icon: true
      display_zero_state: true
      display_zero: true
      unit_white_space: true
      color:
        - 254
        - 203
        - 62
      calculate_flow_rate: true
      show_direction: false
      use_metadata: false
    - entity: sensor.verbrauchsgruppe_haushalt_leistung
      secondary_info: {}
      name: Haushalt
      icon: mdi:stove
      display_zero_state: true
      display_zero: true
      color_value: false
      calculate_flow_rate: true
      show_direction: false
      unit_white_space: true
      color:
        - 135
        - 78
        - 254
      color_icon: true
    - entity: sensor.verbrauchsgruppe_entertainment_leistung
      secondary_info: {}
      name: Entertainment
      icon: mdi:multimedia
      color:
        - 131
        - 17
        - 0
      calculate_flow_rate: true
      unit_white_space: true
      display_zero: true
      display_zero_state: true
    - entity: sensor.verbrauchsgruppe_infrastruktur_wohnung_leistung
      secondary_info: {}
      name: Infrastruktur
      display_zero: true
      display_zero_state: true
      calculate_flow_rate: true
      use_metadata: true
      icon: mdi:server
clickable_entities: true
display_zero_lines:
  mode: transparency
  transparency: 93
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
kw_decimals: 1
min_flow_rate: 0.75
max_expected_power: 13500
min_expected_power: 0.01
watt_threshold: 1000
transparency_zero_lines: 0
dashboard_link: ""
max_flow_rate: 4.5
```
