### ISSUE TITLE
[BUG] Can't see more than 4 individuals in flow

### ISSUE THREAD

**Issue by budisek** [flixlix/power-flow-card-plus#783]
I have added fifth individual entity but it is not presented in flow. Only first entity has changed the color.

<img width="743" alt="Image" src="https://github.com/user-attachments/assets/e003fb42-08a4-434c-9bc0-243cbcfe8e7f" />

```
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.nodemcu3_sunways_battery_power
    state_of_charge: sensor.nodemcu3_sunways_soc
    color_icon: true
    color_state_of_charge_value: true
    color_circle: true
    color_value: true
  grid:
    entity: sensor.nodemcu3_sunways_total_power_on_meter
    display_state: two_way
    color_icon: true
    color_circle: true
    secondary_info:
      template: ""
      entity: sensor.nodemcu3_grid_purchasing_energy_on_that_day_meter
      unit_of_measurement: kWh
      color_value: true
    invert_state: true
    color_value: true
    power_outage:
      entity: sensor.vypadek_proudu
      icon_alert: mdi:transmission-tower-off
      label_alert: Bez proudu
      state_alert: "off"
  solar:
    entity: sensor.nodemcu3_sunways_pv_input_total_power
    display_zero_state: true
    secondary_info:
      entity: sensor.nodemcu3_sunways_pv_generation_energy_on_that_day
      unit_of_measurement: kWh
      color_value: true
    color_icon: true
    color_value: true
    invert_state: false
  home:
    entity: sensor.nodemcu3_sunways_current_load_power
    secondary_info:
      entity: sensor.nodemcu3_sunways_loading_energy_on_that_day
      color_value: true
      unit_of_measurement: kWh
    color_icon: true
    subtract_individual: false
    override_state: false
    color_value: true
  fossil_fuel_percentage:
    entity: sensor.grid_fossil_fuel_percentage
    color_icon: true
    display_zero: true
    state_type: percentage
    color_value: true
    display_zero_state: true
    unit_white_space: false
    secondary_info:
      unit_of_measurement: "%"
      color_value: false
      entity: sensor.grid_fossil_fuel_percentage
      unit_white_space: false
      icon: mdi:molecule-co2
  individual:
    - entity: sensor.tesla_wall_connector_power_total
      name: Tesla
      icon: mdi:car-electric-outline
      color_value: true
      display_zero: true
      display_zero_state: false
      inverted_animation: false
      color_icon: true
      secondary_info:
        unit_of_measurement: "%"
        color_value: true
        entity: sensor.vojtova_tesla_battery
        icon: mdi:battery-medium
      color: orangered
      display_zero_tolerance: 5
      show_direction: false
      use_metadata: false
      calculate_flow_rate: false
      unit_white_space: true
    - entity: sensor.tasmota_energy_power
      name: Bojler
      display_zero: true
      icon: mdi:water-boiler
      color_value: true
      color_icon: true
      color: BlueViolet
      secondary_info:
        entity: sensor.nodemcu2_bojler_teplota_bojler
        unit_of_measurement: °C
        color_value: true
        icon: mdi:thermometer
        unit_white_space: false
        display_zero: true
      display_zero_tolerance: 20
      display_zero_state: false
      unit_white_space: true
    - entity: sensor.wallbox_pulsar_max_sn_910799_nabijeci_vykon
      secondary_info:
        entity: sensor.volvo_yv12zel98ss102976_battery_charge_level
        unit_of_measurement: "%"
        icon: mdi:battery-medium
        color_value: true
      color: DarkTurquoise
      display_zero: true
      icon: mdi:car-electric
      name: Volvo EX30
      color_icon: true
      color_value: true
      unit_white_space: true
      display_zero_tolerance: 5
      display_zero_state: false
    - entity: sensor.cerpadlo_power_total
      name: TČ
      display_zero: true
      icon: mdi:heat-pump-outline
      color_value: true
      color_icon: true
      color: gold
      secondary_info:
        entity: sensor.tasmota_energy_today_2
        unit_of_measurement: kWh
        color_value: true
        icon: ""
        unit_white_space: true
        display_zero: true
      display_zero_tolerance: 10
      display_zero_state: false
      unit_white_space: true
      calculate_flow_rate: false
      decimals: 1
    - entity: sensor.thermostat_1_power
      secondary_info: {}
      name: Podlaha
      display_zero: true
      display_zero_state: true
      color_value: true
      color_icon: true
clickable_entities: true
display_zero_lines:
  mode: transparency
  transparency: 80
  grey_color:
    - 189
    - 189
    - 189
use_new_flow_rate_model: true
w_decimals: 0
max_expected_power: 2000
min_expected_power: 0.01
watt_threshold: 1000
title: Aktuální energie
dashboard_link: ""
min_flow_rate: 2
kw_decimals: 1
disable_dots: false
```
