### ISSUE TITLE
[FEATURE REQUEST] I cannot see an option, thus, would it be possible to use negative and positive values to determine battery charge/discharge rate?

### ISSUE THREAD

**Issue by zs3y** [flixlix/power-flow-card-plus#79]
My inverter supplies one value for charge/discharge rate of the battery for Amperes and again one value in Watt, so there is no charge or discharge value other than the fact that a positive number charges the battery and a negative number discharges the battery.

If possible, could a combined entry be used that automatically based on positive or negative values displays charge or discharge rate/value?

I'm being a bit daft today and can't think of alternatives, but part of the problem is that I'm still learning about Home Assistant and there may be a way to generate the separate charge and discharge entities in Home Assistant, just I am not aware how to, assuming it is possible.

**Comment by flixlix** [comment]
Yes, this is already possible, using:

```yaml
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_power
```

In case your battery power is going in the opposite direction, you can use this configuration:

```yaml
type: custom:power-flow-card-plus
entities:
  battery:
    entity: sensor.battery_power
inverted_entities: battery
```
