### ISSUE TITLE
double_tap_action and hold_action do not work

### ISSUE THREAD

**Issue by ppanish** [flixlix/power-flow-card-plus#808]
**Bug: `double_tap_action` and `hold_action` do not work at any level**

**Description:**
The `double_tap_action` and `hold_action` fields are silently ignored both at the card level and within individual components like `battery`, `grid`, `solar`, etc. This behavior contradicts the expected behavior from other Lovelace cards and is not documented as a limitation.

**Expected Behavior:**
- `double_tap_action` and `hold_action` should be executed when the respective gestures are performed.
- If unsupported, they should produce a warning or be removed from documentation.

**Example YAML:**
```yaml
type: custom:power-flow-card-plus
title: Power Flow
double_tap_action:
  action: more-info
  entity: sensor.aggregate_batteries_voltage
tap_action:
  action: more-info
  entity: sensor.aggregate_batteries_power
battery:
  entity: sensor.aggregate_batteries_power
```

**Observed Behavior:**
Only `tap_action` executes. All other actions are silently ignored.

**Versions:**
- Home Assistant: core-2025.4.3
- Power Flow Card Plus: 0.2.5
