### ISSUE TITLE
display_state one_way not working [BUG]

### ISSUE THREAD

**Issue by benquan** [flixlix/power-flow-card-plus#96]
**Describe the bug**
display_state one_way not working

**To Reproduce**
This is my current configuration:
```
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.hem5_from_grid
      production: sensor.hem5_to_grid
      display_state: one_way
      color_circle: true
  solar:
    entity: sensor.nep_power
kw_decimals: 0
w_decimals: 0
watt_threshold: 1000
```

**Expected behavior**
When I am injecting to the grid I would expect the "0" consumption to hide

**Screenshots**
<img width="474" alt="Screenshot 2023-04-17 at 9 28 58 AM" src="https://user-images.githubusercontent.com/3030645/232535638-622a8e68-021e-437e-8b95-d169b7dfe019.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/power-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Your code is not correctly indented, it should be like this:

```yaml
type: custom:power-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.hem5_from_grid
      production: sensor.hem5_to_grid
    display_state: one_way
    color_circle: true
  solar:
    entity: sensor.nep_power
kw_decimals: 0
w_decimals: 0
watt_threshold: 1000
```
Does this solve the issue?
