### ISSUE TITLE
[FEATURE REQUEST] Nesting configs for individuals

### ISSUE THREAD

**Issue by wltbenade** [flixlix/power-flow-card-plus#97]
**Is your feature request related to a problem? Please describe.**
I have a sprawl of DBs daisy-chained across my property, and would like to have that chain represented.

**Describe the solution you'd like**
I envision the individual power monitoring points in each DBs' configurations being nested under their parent, e.g.
```yaml
individual1:
    entity: sensor.cottage
    icon: mdi:home
    color: '#80b8ff'
    name: Cottage
    color_icon: false
    subs:
      individual1:
      entity: sensor.koi_pond
      icon: mdi:fish
      color: '#80b8ff'
      name: Koi Pond
      color_icon: false
    individual2:
      entity: sensor.electric_fence
      name: Electric Fence
      color_icon: true
      display_zero: true
      color: '#ff8080'
      icon: mdi:motorbike-electric
  individual2:
    entity: sensor.motorbike_power
    name: Qivi
    color_icon: true
    display_zero: true
    color: '#ff8080'
    icon: mdi:motorbike-electric
```

**Describe alternatives you've considered**
I suppose an alternative would be to publish multiple cards.

**Additional context**
N/A
