### ISSUE TITLE
[BUG] color_icon and color_circle options not working as expected for Grid circle/icon

### ISSUE THREAD

**Issue by kantokant** [flixlix/power-flow-card-plus#98]
Seems to me that the color_icon and color_circle options do not work as expected for the grid circle?

Both options are great with the Solar and Home circle, but I can't achieve to dynamically color the Grid circle and icon according to grid consumption and production

Is that a bug in the card or again just a bug in my head? 😊

pic1: grid consumption is higher than production, grid circle is blue (correct) and grid icon is white (should be blue)
![grafik](https://user-images.githubusercontent.com/84535850/232981110-9489f066-8259-4146-8098-f23fce9c4b7b.png)

pic2: grid consumption is lower than production, grid circle should is still blue (should be magenta) and grid icon is white (should be magenta)
![grafik](https://user-images.githubusercontent.com/84535850/232981278-864a08b3-ffe5-4199-b403-f59e6bd1f872.png)

```
type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.rct_power_storage_dc10_consumer_power
    name: Home
    color_icon: true
    secondary_info:
      entity: sensor.rct_power_storage_dc10_grid_power_eurosaldo_hourly
      unit_of_measurement: Ct/h
  grid:
    entity:
      consumption: sensor.rct_power_storage_dc10_grid_power_consumption
      production: sensor.rct_power_storage_dc10_grid_power_production
      display_state: two_way
      color_circle: true
      color_icon: true
  solar:
    name: PV
    icon: mdi:white-balance-sunny
    color_icon: true
    entity: sensor.rct_power_storage_dc10_all_generators_power
    secondary_info:
      entity: sensor.rct_power_storage_dc10_all_generators_power_percentage
      unit_of_measurement: '%'
watt_threshold: 50000
w_decimals: 0
clickable_entities: true
```

**Comment by kantokant** [comment]
aargh stupid me, you're right

Now it's perfect, thanks again for your great work! 👍🚀

![grafik](https://user-images.githubusercontent.com/84535850/233019227-687a32bb-7e57-4a67-99bf-965bd54fde7f.png)
```

type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.rct_power_storage_dc10_consumer_power
    name: Home
    color_icon: true
    secondary_info:
      entity: sensor.rct_power_storage_dc10_grid_power_eurosaldo_hourly
      unit_of_measurement: Ct/h
      display_zero_tolerance: -10000
  grid:
    entity: sensor.rct_power_storage_dc10_grid_power
    color_circle: true
    color_icon: true
    name: Grid
  solar:
    name: PV
    icon: mdi:white-balance-sunny
    color_icon: true
    entity: sensor.rct_power_storage_dc10_all_generators_power
    secondary_info:
      entity: sensor.rct_power_storage_dc10_all_generators_power_percentage
      unit_of_measurement: '%'
watt_threshold: 50000
w_decimals: 0
clickable_entities: true
```
