### ISSUE TITLE
[FEATURE REQUEST] Name and Icon from Entity.

### ISSUE THREAD

**Issue by mariojungwirth** [flixlix/power-flow-card-plus#99]
First of all. I love this card.

It would be very helpful if the name and the icon can be defined via an entity or entity-attribute.

Example:

```yaml
individual1:
  entity: sensor.load_1_usage_w
  icon: sensor.load_1_icon
  name: sensor.load_1_name
  display_zero: false
```
